force-app/main/default/objects/Campaign/fields/Nome_Donatore__c.field-meta.xml
<CustomField>
    <fullName>Nome_Donatore__c</fullName>
    <formula>Donatore__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Donatore</label>
    <type>Text</type>
</CustomField>

mdapi/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Fattura</label>
    <nameField>
        <displayFormat>Fattura-{00000000}</displayFormat>
        <label>Codice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fatture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Data_di_Competenza__c.field-meta.xml
<CustomField>
    <fullName>Data_di_Competenza__c</fullName>
    <label>Data di Competenza</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Medical_Center__c.field-meta.xml
<CustomField>
    <fullName>Medical_Center__c</fullName>
    <label>Medical Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <formula>IF( Budget__r.Program__r.Name = &quot;Tempo Sospeso&quot;,  Totale_Ammontare_Visite__c , IF(Budget__r.Program__r.Name = &quot;Sorriso Sospeso&quot;,  Totale_Ammontare_Biglietti__c , 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceService.cls
public with sharing class InvoiceService {
  @AuraEnabled(cacheable=true)
  public static List<Invoice__c> getInvoices(
    Date campaignStartDate,
    Date campaignEndDate
  ) {
    try {
      // Query per recuperare i record Invoice__c con i campi necessari
      return [
        SELECT
          Id,
          Name,
          Campaign__c,
          Campaign__r.Name,
          Date__c,
          Data_di_Competenza__c,
          Medical_Center__c,
          Nome_Donatore__c,
          Invoice_Number__c,
          Totale_Fattura__c
        FROM Invoice__c
        WHERE
          Data_di_Competenza__c >= :campaignStartDate
          AND Data_di_Competenza__c <= :campaignEndDate
      ];
    } catch (Exception e) {
      throw new AuraHandledException(
        'Errore nel recupero delle fatture: ' + e.getMessage()
      );
    }
  }
}