force-app/main/default/objects/Donor_Overview__c/Donor_Overview__c.object-meta.xml
<CustomObject>
    <label>Donatore per Programma</label>
    <nameField>
        <label>Donor Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Programma</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Donor_Overview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donors Overview</relationshipLabel>
    <relationshipName>Donors_Overview</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Donor_Overview__c/fields/Holding__c.field-meta.xml
<CustomField>
    <fullName>Holding__c</fullName>
    <formula>Account__r.Parent.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Holding</label>
    <type>Text</type>
</CustomField>

mdapi/objects/Donor_Overview__c/fields/Nome_Donatore__c.field-meta.xml
<CustomField>
    <fullName>Nome_Donatore__c</fullName>
    <formula>Account__r.Nome_Donatore__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Donatore</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Overview__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori</relationshipLabel>
    <relationshipName>Overview_Donatori</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donor_Overview__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <summarizedField>Reporting_Year__c.Total_Invoice_Amount__c</summarizedField>
    <summaryForeignKey>Reporting_Year__c.Donor_Overview__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Ammontare_Originale_Donato_Anno_Corrente__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Originale_Donato_Anno_Corrente__c</fullName>
    <label>Ammontare Originale Donato Anno Corrente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Anno_overview__c.field-meta.xml
<CustomField>
    <fullName>Anno_overview__c</fullName>
    <formula>Anno__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Anno</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <formula>Current_Year_Donation_Amount__c -  Total_Invoice_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Current_Year_Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Donation_Amount__c</fullName>
    <label>Current Year Donation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Current_Year_Donation_Number__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Donation_Number__c</fullName>
    <label>Current Year Donation Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Donor_Overview__c.field-meta.xml
<CustomField>
    <fullName>Donor_Overview__c</fullName>
    <label>Donor Overview</label>
    <referenceTo>Donor_Overview__c</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori per Anno</relationshipLabel>
    <relationshipName>Overview_Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totale_Numero_di_Fatture__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Fatture__c</fullName>
    <label>Totale Numero di Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/classes/RetrieveDonatoreProgramma.cls
public with sharing class RetrieveDonatoreProgramma {

    public class DonatoreDataWrapper {
        @AuraEnabled public List<Reporting_Year__c> records;
        @AuraEnabled public List<ProgramFieldConfigUtil.FieldConf> dynamicFields;
    }

    @AuraEnabled(cacheable=true)
    public static DonatoreDataWrapper getRawRecords(Id parentId) {
        if (parentId == null) return new DonatoreDataWrapper();

        Reporting_Year__c root = [
            SELECT Id, Programma__c, Programma__r.Name
            FROM Reporting_Year__c
            WHERE Donor_Overview__c = :parentId
            LIMIT 1
        ];

        if (root.Programma__c == null) return new DonatoreDataWrapper();

        String programLabel = root.Programma__r.Name;
        String programDevName = programLabel.replace(' ', '_');

        Set<String> targets = new Set<String>{ 'Reporting_Year__c' };
        Map<String, List<ProgramFieldConfigUtil.FieldConf>> confMap =
            ProgramFieldConfigUtil.getFieldConfig(programDevName, targets, null);
        List<ProgramFieldConfigUtil.FieldConf> dynamicFields = confMap.get('Reporting_Year__c');

        List<String> baseFields = new List<String>{
            'Id', 'Name', 'Account__c', 'Holding__c', 'Donor_Overview__c', 'Nome_Donatore__c', 'Anno_overview__c',
            'Ammontare_Originale_Donato_Anno_Corrente__c',
            'Available_Amount__c',
            'Current_Year_Donation_Amount__c',
            'Current_Year_Donation_Number__c',
            'Total_Invoice_Amount__c',
            'Totale_Numero_di_Fatture__c'
        };

        for (ProgramFieldConfigUtil.FieldConf f : dynamicFields) {
            if (!baseFields.contains(f.fieldApi)) {
                baseFields.add(f.fieldApi);
            }
        }

        String query =
            'SELECT ' + String.join(baseFields, ', ') +
            ' FROM Reporting_Year__c' +
            ' WHERE Programma__c = \'' + String.escapeSingleQuotes(root.Programma__c) + '\'';

        List<Reporting_Year__c> records = Database.query(query);

        DonatoreDataWrapper result = new DonatoreDataWrapper();
        result.records = records;
        result.dynamicFields = dynamicFields;
        return result;
    }
}