mdapi/objects/Anno_Reportistica__c/Anno_Reportistica__c.object-meta.xml
<CustomObject>
    <label>Anno Reportistica</label>
    <nameField>
        <label>Anno di Reportistica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anni Reportistica</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Anno_Reportistica__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Anni Reportistica</relationshipLabel>
    <relationshipName>Anni_Reportistica</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/Overview_Budget_per_Anno__c.object-meta.xml
<CustomObject>
    <label>Budget per Anno</label>
    <nameField>
        <label>Codice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Ammontare_Pagamenti_Da_Pagare__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Pagamenti_Da_Pagare__c</fullName>
    <label>Ammontare Pagamenti Da Pagare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Ammontare_Pagamenti_Da_Pagare_formula__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Pagamenti_Da_Pagare_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Ammontare_Pagamenti_Da_Pagare__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ammontare Pagamenti Da Pagare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Ammontare_Pagamenti_Fatti__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Pagamenti_Fatti__c</fullName>
    <label>Ammontare Pagamenti Fatti</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Ammontare_Pagamenti_Fatti_formula__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Pagamenti_Fatti_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Ammontare_Pagamenti_Fatti__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ammontare Pagamenti Fatti</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Anno_Reportistica__c.field-meta.xml
<CustomField>
    <fullName>Anno_Reportistica__c</fullName>
    <label>Anno Reportistica</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Numero_di_Fatture__c.field-meta.xml
<CustomField>
    <fullName>Numero_di_Fatture__c</fullName>
    <label>Numero di Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Numero_di_Fatture_formula__c.field-meta.xml
<CustomField>
    <fullName>Numero_di_Fatture_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Numero_di_Fatture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero di Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Numero_Distribuzioni__c.field-meta.xml
<CustomField>
    <fullName>Numero_Distribuzioni__c</fullName>
    <label>Numero Distribuzioni</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Numero_Distribuzioni_Formula__c.field-meta.xml
<CustomField>
    <fullName>Numero_Distribuzioni_Formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Numero_Allocazioni_Budget__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero Distribuzioni</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Ammontare_Fatture__c.field-meta.xml
<CustomField>
    <fullName>Totale_Ammontare_Fatture__c</fullName>
    <label>Totale Ammontare Fatture</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Totale_Ammontare_Fatture_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Ammontare_Fatture_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Ammontare_Fatture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Ammontare Fatture</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Distribuito_NON_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Distribuito_NON_Pagato__c</fullName>
    <label>Totale Distribuito NON Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Distribuito_NON_Pagato_Formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Distribuito_NON_Pagato_Formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Allocato_Budget_NON_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Distribuito NON Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Distribuito_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Distribuito_Pagato__c</fullName>
    <label>Totale Distribuito Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Totale_Distribuito_Pagato_Formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Distribuito_Pagato_Formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Allocato_Budget_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Distribuito Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Minuti_di_Visita__c.field-meta.xml
<CustomField>
    <fullName>Totale_Minuti_di_Visita__c</fullName>
    <label>Totale Minuti di Visita</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Minuti_di_Visita_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Minuti_di_Visita_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Minuti_Visite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Minuti di Visita</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Totale_Numero_di_Visite__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Visite__c</fullName>
    <label>Totale Numero di Visite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Numero_di_Visite_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Visite_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Numero_Visite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Numero di Visite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Reporting_Year__c/fields/Ammontare_Originale_Donato_Anno_Corrente__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Originale_Donato_Anno_Corrente__c</fullName>
    <label>Ammontare Originale Donato Anno Corrente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Anni di Reportistica</relationshipLabel>
    <relationshipName>Anni_di_Reportistica</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Current_Year_Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Donation_Amount__c</fullName>
    <label>Current Year Donation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Current_Year_Donation_Number__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Donation_Number__c</fullName>
    <label>Current Year Donation Number</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Donato_Originale_formula__c.field-meta.xml
<CustomField>
    <fullName>Donato_Originale_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Donato_Originale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Donato Originale</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori per Anno</relationshipLabel>
    <relationshipName>Overview_Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Total_Minutes_of_Visits__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes_of_Visits__c</fullName>
    <label>Total Minutes of Visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Total_Visits_done__c.field-meta.xml
<CustomField>
    <fullName>Total_Visits_done__c</fullName>
    <label>Total Visits done</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Totale_Allocato_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Allocato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Allocato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Totale_Durata_Visite_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Durata_Visite_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Durata_Visite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Durata Visite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totale_Fattura_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Fattura__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totale_Numero_di_Fatture__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Fatture__c</fullName>
    <label>Totale Numero di Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totale_Numero_di_Visite_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Visite_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Numero_di_Visite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Numero di Visite</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Totale_Numero_Donazioni_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_Donazioni_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Numero_Donazioni__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Numero Donazioni</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Totale_Numero_Fatture_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_Fatture_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Numero_Fatture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Numero Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StaticFieldsCopy.cls
public with sharing class StaticFieldsCopy {

    public class InputWrapper {
        @InvocableVariable(required=false)
        public String recordId;

        @InvocableVariable(required=false)
        public String programId;
    }

    public class OutputWrapper {
        @InvocableVariable
        public String message;
    }

    @InvocableMethod(label='Copia Valori da Campi Formula' description='Copia i valori statici dai campi formula per Anno e Programma')
    public static List<OutputWrapper> copiaValori(List<InputWrapper> inputList) {
        InputWrapper input = inputList[0];
        copiaValoriInterna(input.recordId, input.programId);

        OutputWrapper out = new OutputWrapper();
        out.message = 'Copia completata';
        return new List<OutputWrapper>{ out };
    }

    public static void copiaValoriInterna(String recordId, String programId) {
        // ------------------------
        // Query per BUDGET
        // ------------------------
        String budgetQuery = 
            'SELECT Id, Programma__c, Ammontare_Pagamenti_Da_Pagare_formula__c, Ammontare_Pagamenti_Fatti_formula__c, ' +
            'Numero_di_Fatture_formula__c, Numero_Distribuzioni_Formula__c, Totale_Ammontare_Fatture_formula__c, ' +
            'Totale_Distribuito_NON_Pagato_Formula__c, Totale_Distribuito_Pagato_Formula__c, Totale_Minuti_di_Visita_formula__c, ' +
            'Totale_Numero_di_Visite_formula__c, Ammontare_Pagamenti_Da_Pagare__c, Ammontare_Pagamenti_Fatti__c, ' +
            'Numero_di_Fatture__c, Numero_Distribuzioni__c, Totale_Ammontare_Fatture__c, Totale_Distribuito_NON_Pagato__c, ' +
            'Totale_Distribuito_Pagato__c, Totale_Minuti_di_Visita__c, Totale_Numero_di_Visite__c ' +
            'FROM Overview_Budget_per_Anno__c';

    List<String> budgetConditions = new List<String>();
    if (String.isNotBlank(recordId)) {
        budgetConditions.add('Anno_Reportistica__c = :recordId');
    }
    if (String.isNotBlank(programId)) {
        budgetConditions.add('Programma__c = :programId');
    }
    String budgetWhere = budgetConditions.isEmpty() ? '' : ' WHERE ' + String.join(budgetConditions, ' AND ');
    List<Overview_Budget_per_Anno__c> budgets = Database.query(budgetQuery + budgetWhere);

    // ------------------------
    // Query per REPORTING YEAR
    // ------------------------
    String yearQuery = 
        'SELECT Id, Programma__c, Donato_Originale_formula__c, Totale_Numero_Donazioni_formula__c, Totale_Fattura_formula__c, ' +
        'Totale_Durata_Visite_formula__c, Totale_Numero_di_Visite_formula__c, Totale_Numero_Fatture_formula__c, ' +
        'Totale_Allocato_formula__c, Ammontare_Originale_Donato_Anno_Corrente__c, Current_Year_Donation_Number__c, ' +
        'Current_Year_Donation_Amount__c, Total_Minutes_of_Visits__c, Total_Visits_done__c, Totale_Numero_di_Fatture__c, ' +
        'Total_Invoice_Amount__c ' +
        'FROM Reporting_Year__c';

    List<String> yearConditions = new List<String>();
    if (String.isNotBlank(recordId)) {
        yearConditions.add('Anno__c = :recordId');
    }
    if (String.isNotBlank(programId)) {
        yearConditions.add('Programma__c = :programId');
    }
    String yearWhere = yearConditions.isEmpty() ? '' : ' WHERE ' + String.join(yearConditions, ' AND ');
    List<Reporting_Year__c> years = Database.query(yearQuery + yearWhere);

        List<Overview_Budget_per_Anno__c> budgetsToUpdate = new List<Overview_Budget_per_Anno__c>();
        for (Overview_Budget_per_Anno__c b : budgets) {
            Boolean changed = false;
            if (b.Ammontare_Pagamenti_Da_Pagare__c != b.Ammontare_Pagamenti_Da_Pagare_formula__c) {
                b.Ammontare_Pagamenti_Da_Pagare__c = b.Ammontare_Pagamenti_Da_Pagare_formula__c; changed = true;
            }
            if (b.Ammontare_Pagamenti_Fatti__c != b.Ammontare_Pagamenti_Fatti_formula__c) {
                b.Ammontare_Pagamenti_Fatti__c = b.Ammontare_Pagamenti_Fatti_formula__c; changed = true;
            }
            if (b.Numero_di_Fatture__c != b.Numero_di_Fatture_formula__c) {
                b.Numero_di_Fatture__c = b.Numero_di_Fatture_formula__c; changed = true;
            }
            if (b.Numero_Distribuzioni__c != b.Numero_Distribuzioni_Formula__c) {
                b.Numero_Distribuzioni__c = b.Numero_Distribuzioni_Formula__c; changed = true;
            }
            if (b.Totale_Ammontare_Fatture__c != b.Totale_Ammontare_Fatture_formula__c) {
                b.Totale_Ammontare_Fatture__c = b.Totale_Ammontare_Fatture_formula__c; changed = true;
            }
            if (b.Totale_Distribuito_NON_Pagato__c != b.Totale_Distribuito_NON_Pagato_Formula__c) {
                b.Totale_Distribuito_NON_Pagato__c = b.Totale_Distribuito_NON_Pagato_Formula__c; changed = true;
            }
            if (b.Totale_Distribuito_Pagato__c != b.Totale_Distribuito_Pagato_Formula__c) {
                b.Totale_Distribuito_Pagato__c = b.Totale_Distribuito_Pagato_Formula__c; changed = true;
            }
            if (b.Totale_Minuti_di_Visita__c != b.Totale_Minuti_di_Visita_formula__c) {
                b.Totale_Minuti_di_Visita__c = b.Totale_Minuti_di_Visita_formula__c; changed = true;
            }
            if (b.Totale_Numero_di_Visite__c != b.Totale_Numero_di_Visite_formula__c) {
                b.Totale_Numero_di_Visite__c = b.Totale_Numero_di_Visite_formula__c; changed = true;
            }

            if (changed) budgetsToUpdate.add(b);
        }

        List<Reporting_Year__c> yearsToUpdate = new List<Reporting_Year__c>();
        for (Reporting_Year__c y : years) {
            Boolean changed = false;
            if (y.Ammontare_Originale_Donato_Anno_Corrente__c != y.Donato_Originale_formula__c) {
                y.Ammontare_Originale_Donato_Anno_Corrente__c = y.Donato_Originale_formula__c; changed = true;
            }
            if (y.Current_Year_Donation_Number__c != y.Totale_Numero_Donazioni_formula__c) {
                y.Current_Year_Donation_Number__c = y.Totale_Numero_Donazioni_formula__c; changed = true;
            }
            if (y.Current_Year_Donation_Amount__c != y.Totale_Allocato_formula__c) {
                y.Current_Year_Donation_Amount__c = y.Totale_Allocato_formula__c; changed = true;
            }
            if (y.Total_Minutes_of_Visits__c != y.Totale_Durata_Visite_formula__c) {
                y.Total_Minutes_of_Visits__c = y.Totale_Durata_Visite_formula__c; changed = true;
            }
            if (y.Total_Visits_done__c != y.Totale_Numero_di_Visite_formula__c) {
                y.Total_Visits_done__c = y.Totale_Numero_di_Visite_formula__c; changed = true;
            }
            if (y.Totale_Numero_di_Fatture__c != y.Totale_Numero_Fatture_formula__c) {
                y.Totale_Numero_di_Fatture__c = y.Totale_Numero_Fatture_formula__c; changed = true;
            }
            if (y.Total_Invoice_Amount__c != y.Totale_Fattura_formula__c) {
                y.Total_Invoice_Amount__c = y.Totale_Fattura_formula__c; changed = true;
            }

            if (changed) yearsToUpdate.add(y);
        }

        if (!budgetsToUpdate.isEmpty()) update budgetsToUpdate;
        if (!yearsToUpdate.isEmpty()) update yearsToUpdate;
    }
}