mdapi/objects/Anno_Reportistica__c/Anno_Reportistica__c.object-meta.xml
<CustomObject>
    <label>Anno Reportistica</label>
    <nameField>
        <label>Anno di Reportistica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anni Reportistica</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Anno_Reportistica__c/fields/Ammontare_Distribuzioni__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Distribuzioni__c</fullName>
    <label>Ammontare Distribuzioni</label>
    <summarizedField>Overview_Budget_per_Anno__c.Totale_Allocato__c</summarizedField>
    <summaryForeignKey>Overview_Budget_per_Anno__c.Anno_Reportistica__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Anno_Reportistica__c/fields/Ammontare_Distribuzioni_Pagate__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Distribuzioni_Pagate__c</fullName>
    <label>Ammontare Distribuzioni Pagate</label>
    <summarizedField>Overview_Budget_per_Anno__c.Totale_Distribuito_Pagato__c</summarizedField>
    <summaryForeignKey>Overview_Budget_per_Anno__c.Anno_Reportistica__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Anno_Reportistica__c/fields/Ammontare_Originale_Donato__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Originale_Donato__c</fullName>
    <label>Ammontare Originale Donato</label>
    <summarizedField>Reporting_Year__c.Ammontare_Originale_Donato_Anno_Corrente__c</summarizedField>
    <summaryForeignKey>Reporting_Year__c.Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Anno_Reportistica__c/fields/Capienza_budgets__c.field-meta.xml
<CustomField>
    <fullName>Capienza_budgets__c</fullName>
    <formula>Ammontare_Distribuzioni__c -  Totale_Fatturato_Budgets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capienza - budgets</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Anno_Reportistica__c/fields/Numero_Donazioni_Anno_Corrente__c.field-meta.xml
<CustomField>
    <fullName>Numero_Donazioni_Anno_Corrente__c</fullName>
    <label>Numero Donazioni Anno Corrente</label>
    <summarizedField>Reporting_Year__c.Current_Year_Donation_Number__c</summarizedField>
    <summaryForeignKey>Reporting_Year__c.Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Anno_Reportistica__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Anni Reportistica</relationshipLabel>
    <relationshipName>Anni_Reportistica</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Anno_Reportistica__c/fields/Totale_Allocabile__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocabile__c</fullName>
    <label>Totale Allocabile</label>
    <summarizedField>Reporting_Year__c.Current_Year_Donation_Amount__c</summarizedField>
    <summaryForeignKey>Reporting_Year__c.Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Anno_Reportistica__c/fields/Totale_Fatturato_Budgets__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fatturato_Budgets__c</fullName>
    <label>Totale Fatturato</label>
    <summarizedField>Overview_Budget_per_Anno__c.Totale_Ammontare_Fatture__c</summarizedField>
    <summaryForeignKey>Overview_Budget_per_Anno__c.Anno_Reportistica__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Anno_Reportistica__c/fields/Totale_NON_Distribuito__c.field-meta.xml
<CustomField>
    <fullName>Totale_NON_Distribuito__c</fullName>
    <formula>Totale_Allocabile__c -  Ammontare_Distribuzioni__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale NON Distribuito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Anno_Reportistica__c/fields/Totale_Numero_Fatture__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_Fatture__c</fullName>
    <label>Totale Numero Fatture</label>
    <summarizedField>Overview_Budget_per_Anno__c.Numero_di_Fatture__c</summarizedField>
    <summaryForeignKey>Overview_Budget_per_Anno__c.Anno_Reportistica__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program/fields/Ammontare_Distribuzioni__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Distribuzioni__c</fullName>
    <label>Ammontare Distribuzioni</label>
    <summarizedField>Anno_Reportistica__c.Ammontare_Distribuzioni__c</summarizedField>
    <summaryForeignKey>Anno_Reportistica__c.Programma__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program/fields/Ammontare_Originale_Donato__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Originale_Donato__c</fullName>
    <label>Ammontare Originale Donato</label>
    <summarizedField>Anno_Reportistica__c.Ammontare_Originale_Donato__c</summarizedField>
    <summaryForeignKey>Anno_Reportistica__c.Programma__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Program_Config__mdt/Program_Config__mdt.object-meta.xml
<CustomObject>
    <label>Program Config</label>
    <pluralLabel>Program Configs</pluralLabel>
</CustomObject>

mdapi/objects/Program_Field_Config__mdt/Program_Field_Config__mdt.object-meta.xml
<CustomObject>
    <label>Program Field Config</label>
    <pluralLabel>Program Field Configs</pluralLabel>
</CustomObject>

mdapi/objects/Program_Field_Config__mdt/fields/Target_Object_API__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_API__c</fullName>
    <label>Target Object API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/classes/ListViewAnnoReportistica.cls
public with sharing class ListViewAnnoReportistica {
  @AuraEnabled(cacheable=true)
  public static List<AnnoReportisticaWrapper> getAnnoReportisticaData() {
    final String TARGET_OBJECT = 'Anno_Reportistica__c';

    /* ----------------------------------------------------
     * 1. Recupero campi dinamici da Program_Field_Config
     * --------------------------------------------------*/
    Set<String> dynamicFieldSet = new Set<String>();

    for (Program_Field_Config__mdt cfg : [
      SELECT Field_API__c
      FROM Program_Field_Config__mdt
      WHERE Target_Object_API__c = :TARGET_OBJECT
    ]) {
      dynamicFieldSet.add(cfg.Field_API__c);
    }

    /* ----------------------------------------------------
     * 2. Costruzione lista completa di campi da selezionare
     * --------------------------------------------------*/
    List<String> baseFields = new List<String>{
      'Name',
      'Id',
      'Ammontare_Originale_Donato__c',
      'Totale_Allocabile__c',
      'Ammontare_Distribuzioni__c',
      'Ammontare_Distribuzioni_Pagate__c',
      'Totale_NON_Distribuito__c',
      'Numero_Donazioni_Anno_Corrente__c',
      'Totale_Fatturato_Budgets__c',
      'Capienza_budgets__c',
      'Totale_Numero_Fatture__c',
      'Programma__c',
      'Programma__r.Name'
    };
    baseFields.addAll(dynamicFieldSet);

    String soql =
      'SELECT ' +
      String.join(baseFields, ',') +
      ' FROM Anno_Reportistica__c' +
      ' WHERE Programma__r.Name != null';

    List<Anno_Reportistica__c> records = Database.query(soql);

    /* ----------------------------------------------------
     * 3. Resto del metodo invariato
     * --------------------------------------------------*/
    Map<String, String> nameToDevMap = getProgramNameToDevNameMap();
    List<AnnoReportisticaWrapper> result = new List<AnnoReportisticaWrapper>();

    for (Anno_Reportistica__c record : records) {
      String programLabel = record.Programma__r.Name;
      String programDevName = nameToDevMap.get(programLabel);
      if (programDevName == null)
        programDevName = programLabel.replace(' ', '_');

      Map<String, List<ProgramFieldConfigUtil.FieldConf>> fieldConfMap = ProgramFieldConfigUtil.getFieldConfig(
        programDevName,
        new Set<String>{ TARGET_OBJECT },
        null
      );

      List<ProgramFieldConfigUtil.FieldConf> dynamicFields = fieldConfMap.get(
        TARGET_OBJECT
      );
      result.add(new AnnoReportisticaWrapper(record, dynamicFields));
    }
    return result;
  }

  private static Map<String, String> getProgramNameToDevNameMap() {
    Map<String, String> result = new Map<String, String>();
    for (Program_Config__mdt conf : [
      SELECT DeveloperName, MasterLabel
      FROM Program_Config__mdt
    ]) {
      result.put(conf.MasterLabel, conf.DeveloperName);
    }
    return result;
  }

  public class AnnoReportisticaWrapper {
    @AuraEnabled
    public Anno_Reportistica__c record;
    @AuraEnabled
    public List<ProgramFieldConfigUtil.FieldConf> dynamicFields;

    public AnnoReportisticaWrapper(
      Anno_Reportistica__c r,
      List<ProgramFieldConfigUtil.FieldConf> fields
    ) {
      this.record = r;
      this.dynamicFields = fields != null
        ? fields
        : new List<ProgramFieldConfigUtil.FieldConf>();
    }
  }
}