mdapi/objects/Anno_Reportistica__c/Anno_Reportistica__c.object-meta.xml
<CustomObject>
    <label>Anno Reportistica</label>
    <nameField>
        <label>Anno di Reportistica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anni Reportistica</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Anno_Reportistica__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Anni Reportistica</relationshipLabel>
    <relationshipName>Anni_Reportistica</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donor_Overview__c/Donor_Overview__c.object-meta.xml
<CustomObject>
    <label>Donatore per Programma</label>
    <nameField>
        <label>Donor Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Programma</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Donor_Overview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donors Overview</relationshipLabel>
    <relationshipName>Donors_Overview</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Donor_Overview__c/fields/Holding__c.field-meta.xml
<CustomField>
    <fullName>Holding__c</fullName>
    <formula>Account__r.Parent.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Holding</label>
    <type>Text</type>
</CustomField>

mdapi/objects/Donor_Overview__c/fields/Nome_Donatore__c.field-meta.xml
<CustomField>
    <fullName>Nome_Donatore__c</fullName>
    <formula>Account__r.Nome_Donatore__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Donatore</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Overview__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori</relationshipLabel>
    <relationshipName>Overview_Donatori</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GiftDesignation/fields/Totale_Allocato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato__c</fullName>
    <label>Totale Allocato</label>
    <summarizedField>Overview_Budget_per_Anno__c.Totale_Allocato__c</summarizedField>
    <summaryForeignKey>Overview_Budget_per_Anno__c.Budget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/Overview_Budget_per_Anno__c.object-meta.xml
<CustomObject>
    <label>Budget per Anno</label>
    <nameField>
        <label>Codice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Ammontare_Pagamenti_Da_Pagare_formula__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Pagamenti_Da_Pagare_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Ammontare_Pagamenti_Da_Pagare__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ammontare Pagamenti Da Pagare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Ammontare_Pagamenti_Fatti_formula__c.field-meta.xml
<CustomField>
    <fullName>Ammontare_Pagamenti_Fatti_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Ammontare_Pagamenti_Fatti__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ammontare Pagamenti Fatti</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Anno_Reportistica__c.field-meta.xml
<CustomField>
    <fullName>Anno_Reportistica__c</fullName>
    <label>Anno Reportistica</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Numero_di_Fatture_formula__c.field-meta.xml
<CustomField>
    <fullName>Numero_di_Fatture_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Numero_di_Fatture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero di Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Numero_Distribuzioni_Formula__c.field-meta.xml
<CustomField>
    <fullName>Numero_Distribuzioni_Formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Numero_Allocazioni_Budget__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero Distribuzioni</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Totale_Allocato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato__c</fullName>
    <formula>Totale_Distribuito_Pagato__c +  Totale_Distribuito_NON_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Allocato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Totale_Ammontare_Fatture_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Ammontare_Fatture_formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Ammontare_Fatture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Ammontare Fatture</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totale_Distribuito_NON_Pagato_Formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Distribuito_NON_Pagato_Formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Allocato_Budget_NON_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Distribuito NON Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Totale_Distribuito_Pagato_Formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Distribuito_Pagato_Formula__c</fullName>
    <formula>Totali_Budget_Anno__r.Totale_Allocato_Budget_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Distribuito Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Allocabile_formula__c.field-meta.xml
<CustomField>
    <fullName>Allocabile_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Allocabile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocabile</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Anni di Reportistica</relationshipLabel>
    <relationshipName>Anni_di_Reportistica</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Anno_overview__c.field-meta.xml
<CustomField>
    <fullName>Anno_overview__c</fullName>
    <formula>Anno__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Anno</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <formula>Current_Year_Donation_Amount__c -  Total_Invoice_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Donato_Originale_formula__c.field-meta.xml
<CustomField>
    <fullName>Donato_Originale_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Donato_Originale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Donato Originale</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Donor_Overview__c.field-meta.xml
<CustomField>
    <fullName>Donor_Overview__c</fullName>
    <label>Donor Overview</label>
    <referenceTo>Donor_Overview__c</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori per Anno</relationshipLabel>
    <relationshipName>Overview_Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totale_Fattura_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Fattura__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Totale_Numero_Donazioni_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_Donazioni_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Totale_Numero_Donazioni__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Numero Donazioni</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/fields/Totale_Numero_Fatture_formula__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_Fatture_formula__c</fullName>
    <formula>Totali_Donatore_Anno__r.Numero_Fatture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Numero Fatture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnnoReportistica.cls
public with sharing class AnnoReportistica {

    /**
     * Ritorna:
     *  • records_budget      → lista Overview_Budget_per_Anno__c
     *  • records_donor_raw   → lista Reporting_Year__c
     *  • budgetMeta          → List<FieldConf> (ultime 2 colonne Budget)
     *  • donorMeta           → List<FieldConf> (ultime 2 colonne Donor)
     *  • query_budget / query_donor → stringhe SOQL risolte
     */

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getRelatedRecords(
            String recordId,
            String programDevName        // <— nuovo parametro
    ) {
      
        /* --- validazione minima --- */
        if (String.isBlank(recordId) || (recordId.length() != 15 && recordId.length() != 18)) {
            throw new AuraHandledException('recordId non valido');
        }
        if (String.isBlank(programDevName)) {
            throw new AuraHandledException('Program developer name mancante');
        }

        /* -----------------------------------------------------------
         * 1) Leggi la configurazione dinamica (max 2 KPI per oggetto)
         * ----------------------------------------------------------- */
        Set<String> targetObjs = new Set<String>{
            'Overview_Budget_per_Anno__c',
            'Reporting_Year__c'
        };
        Map<String, List<ProgramFieldConfigUtil.FieldConf>> metaByObj =
            ProgramFieldConfigUtil.getFieldConfig(
                programDevName,
                targetObjs,
                2           // limite colonne dinamiche per oggetto
            );


        /* -----------------------------------------------------------
         * 2) Campi statici + dinamici per Overview_Budget_per_Anno__c
         * ----------------------------------------------------------- */
        List<String> budgetFields = new List<String>{
            'Id','Name','Budget__c','Budget__r.Name','Anno__c',
            'Ammontare_Pagamenti_Da_Pagare_formula__c',
            'Ammontare_Pagamenti_Fatti_formula__c',
            'Numero_di_Fatture_formula__c','Numero_Distribuzioni_Formula__c',
            'Totale_Ammontare_Fatture_formula__c',
            'Totale_Distribuito_NON_Pagato_Formula__c',
            'Totale_Distribuito_Pagato_Formula__c',
            'Totale_Allocato__c'
        };
        for (ProgramFieldConfigUtil.FieldConf f :
             metaByObj.get('Overview_Budget_per_Anno__c')) {
            budgetFields.add(f.fieldApi);
        }

        /* -----------------------------------------------------------
         * 3) Campi statici + dinamici per Reporting_Year__c
         * ----------------------------------------------------------- */
        List<String> donorFields = new List<String>{
            'Id','Name','Account__c','Nome_Donatore__c','Donor_Overview__c',
            'Donor_Overview__r.Name','Year__c','Anno_overview__c',
            'Programma__c','Holding__c',
            'Donato_Originale_formula__c','Available_Amount__c',
            'Allocabile_formula__c','Totale_Numero_Donazioni_formula__c',
            'Totale_Fattura_formula__c',
            'Totale_Numero_Fatture_formula__c'
        };
        for (ProgramFieldConfigUtil.FieldConf f :
             metaByObj.get('Reporting_Year__c')) {
            donorFields.add(f.fieldApi);
        }


        /* -----------------------------------------------------------
         * 4) Costruisci ed esegui le query SOQL
         * ----------------------------------------------------------- */
        String soqlBudget =
            'SELECT ' + String.join(budgetFields, ',') +
            ' FROM Overview_Budget_per_Anno__c' +
            ' WHERE Anno_Reportistica__c = :recordId';

        String soqlDonor  =
            'SELECT ' + String.join(donorFields, ',') +
            ' FROM Reporting_Year__c' +
            ' WHERE Anno__c = :recordId';

        System.debug('SOQL Budget ► ' + soqlBudget);
        System.debug('SOQL Donor  ► ' + soqlDonor);

        List<Overview_Budget_per_Anno__c> recordsBudget =
            Database.query(soqlBudget);
        List<Reporting_Year__c> recordsDonor =
            Database.query(soqlDonor);

        /* -----------------------------------------------------------
         * 5) Costruisci la risposta per il client
         * ----------------------------------------------------------- */
        return new Map<String, Object>{
            'records_budget'    => recordsBudget,
            'records_donor_raw' => recordsDonor,
            'budgetMeta'        => metaByObj.get('Overview_Budget_per_Anno__c'),
            'donorMeta'         => metaByObj.get('Reporting_Year__c'),
            'query_budget'      => soqlBudget,
            'query_donor'       => soqlDonor
        };
    }
}