mdapi/objects/Fattura_Shadow__c/Fattura_Shadow__c.object-meta.xml
<CustomObject>
    <label>Fattura Shadow</label>
    <nameField>
        <label>Fattura Shadow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fatture Shadow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fattura_Shadow__c/fields/Bypass_Flow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se true, il flow record-triggered Aggiorna_Valori_Statici_Fattura_Shadow non viene eseguito. Usato dagli aggiornamenti bulk Apex per evitare il limite DML.</description>
    <label>Bypass Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fattura_Shadow__c/fields/Totale_Durata_Visite_Static__c.field-meta.xml
<CustomField>
    <fullName>Totale_Durata_Visite_Static__c</fullName>
    <label>Totale Durata Visite - Static</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <formula>Fattura__r.Totale_Fattura__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fattura_Shadow__c/fields/Totale_Fattura_Static__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura_Static__c</fullName>
    <label>Totale Fattura - Static</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totale_Numero_di_Biglietti_Static__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Biglietti_Static__c</fullName>
    <label>Totale Numero di Biglietti Static</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fattura_Shadow__c/fields/Totale_Numero_di_Visite_Static__c.field-meta.xml
<CustomField>
    <fullName>Totale_Numero_di_Visite_Static__c</fullName>
    <label>Totale Numero di Visite - Static</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Fattura</label>
    <nameField>
        <displayFormat>Fattura-{00000000}</displayFormat>
        <label>Codice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fatture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Bypass_Flow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flow__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Bypass Flow</label>
    <type>Checkbox</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Fattura_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Fattura_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fattura Shadow</label>
    <referenceTo>Fattura_Shadow__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Overview_Budget_per_Anno__c.field-meta.xml
<CustomField>
    <fullName>Overview_Budget_per_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Budget per Anno</label>
    <referenceTo>Overview_Budget_per_Anno__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <formula>Overview_Budget_per_Anno__r.Programma__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Donatore per Anno</label>
    <referenceTo>Reporting_Year__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Total_Duration_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Duration_in_minutes__c</fullName>
    <label>Total Duration (in minutes)</label>
    <summarizedField>Visit__c.Duration_in_minutes__c</summarizedField>
    <summaryForeignKey>Visit__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Number_of_Visits__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Visits__c</fullName>
    <label>Total Number of Visits</label>
    <summarizedField>Visit__c.Quantity__c</summarizedField>
    <summaryForeignKey>Visit__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Totale_Biglietti__c.field-meta.xml
<CustomField>
    <fullName>Totale_Biglietti__c</fullName>
    <label>Totale Biglietti</label>
    <summarizedField>Ticket__c.Uses__c</summarizedField>
    <summaryForeignKey>Ticket__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <formula>IF( Budget__r.Program__r.Name = &quot;Tempo Sospeso&quot;,  Totale_Ammontare_Visite__c , IF(Budget__r.Program__r.Name = &quot;Sorriso Sospeso&quot;,  Totale_Ammontare_Biglietti__c , 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/Overview_Budget_per_Anno__c.object-meta.xml
<CustomObject>
    <label>Budget per Anno</label>
    <nameField>
        <label>Codice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Budget per Anno</relationshipLabel>
    <relationshipName>Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Reporting_Year__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori per Anno</relationshipLabel>
    <relationshipName>Overview_Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Donatori per Anno</relationshipLabel>
    <relationshipName>Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Totali_Budget_Anno__c/Totali_Budget_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Budget Anno</label>
    <nameField>
        <label>Totali Budget Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Budget Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Totali_Donatore_Anno__c/Totali_Donatore_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Donatore Anno</label>
    <nameField>
        <label>Totali Donatore Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Donatore Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Totali_Donatore_Anno__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <label>Totale Fattura</label>
    <summarizedField>Fattura_Shadow__c.Totale_Fattura_Static__c</summarizedField>
    <summaryForeignKey>Fattura_Shadow__c.Totali_Donatore_Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/InvoiceStaticValuesBatch.cls
/**
 *  InvoiceStaticValuesBatch
 *
 *  Batch Apex che aggiorna Fattura_Shadow__c per le Invoice__c
 *  collegate ai Programmi indicati.
 *  without sharing: necessario per aggiornare Fattura_Shadow collegate
 *  a Totali_* che potrebbero non essere visibili per sharing.
 *
 *  API 63.0
 */
public without sharing class InvoiceStaticValuesBatch implements Database.Batchable<SObject> {
  /*------------------------------------------------------------------
   *  Costruttore
   *----------------------------------------------------------------*/
  private final Set<Id> obIds;
  private final Set<Id> programIds;
  private final Id notifyUserId;

  public InvoiceStaticValuesBatch(Set<Id> programIds) {
    this(programIds, false, null);
  }

  /**
   * @param programIds Programmi da processare
   * @param runContinuation Se true, in finish() lancia AllineaDonatoreAnno e AllineaBudgetAnno
   * @param notifyUserId Utente a cui inviare toast al completamento
   */
  public InvoiceStaticValuesBatch(
    Set<Id> programIds,
    Boolean runContinuation,
    Id notifyUserId
  ) {
    this.programIds = (runContinuation && programIds != null) ? new Set<Id>(programIds) : new Set<Id>();
    this.notifyUserId = notifyUserId;
    this.obIds = new Set<Id>();
    if (programIds != null && !programIds.isEmpty()) {
      for (Overview_Budget_per_Anno__c ob : [
        SELECT Id FROM Overview_Budget_per_Anno__c WHERE Programma__c IN :programIds
      ]) {
        obIds.add(ob.Id);
      }
    }
  }

  /*------------------------------------------------------------------
   *  start - usa Overview_Budget_per_Anno__c (lookup) invece di Programma__c (formula Text)
   *  per compatibilità con tutte le org
   *----------------------------------------------------------------*/
  public Database.QueryLocator start(Database.BatchableContext ctx) {
    if (obIds.isEmpty())
      return Database.getQueryLocator([SELECT Id FROM Invoice__c LIMIT 0]);
    return Database.getQueryLocator(
      [
        SELECT
          Id,
          Fattura_Shadow__c,
          Total_Duration_in_minutes__c,
          Totale_Fattura__c,
          Totale_Biglietti__c,
          Total_Number_of_Visits__c,
          Overview_Budget_per_Anno__r.Totali_Budget_Anno__c,
          Reporting_Year__r.Totali_Donatore_Anno__c
        FROM Invoice__c
        WHERE Overview_Budget_per_Anno__c IN :obIds AND Fattura_Shadow__c != NULL
      ]
    );
  }

  /*------------------------------------------------------------------
   *  execute
   *----------------------------------------------------------------*/
  public void execute(Database.BatchableContext ctx, List<SObject> scope) {
    Map<Id, Fattura_Shadow__c> shadowUpdates = new Map<Id, Fattura_Shadow__c>();

    for (Invoice__c inv : (List<Invoice__c>) scope) {
      if (inv.Fattura_Shadow__c == null)
        continue;

      Fattura_Shadow__c fs = shadowUpdates.get(inv.Fattura_Shadow__c);
      if (fs == null) {
        fs = new Fattura_Shadow__c(Id = inv.Fattura_Shadow__c);
        shadowUpdates.put(fs.Id, fs);
      }

      fs.Bypass_Flow__c = true; /* evita record-triggered flow → limite DML */
      /* campi statici */
      fs.Totale_Durata_Visite_Static__c = inv.Total_Duration_in_minutes__c;
      fs.Totale_Fattura_Static__c = inv.Totale_Fattura__c;
      fs.Totale_Numero_di_Biglietti_Static__c = inv.Totale_Biglietti__c;
      fs.Totale_Numero_di_Visite_Static__c = inv.Total_Number_of_Visits__c;

      fs.Totali_Budget_Anno__c = (inv.Overview_Budget_per_Anno__r != null)
        ? inv.Overview_Budget_per_Anno__r.Totali_Budget_Anno__c
        : null;

      fs.Totali_Donatore_Anno__c = (inv.Reporting_Year__r != null)
        ? inv.Reporting_Year__r.Totali_Donatore_Anno__c
        : null;
    }

    if (!shadowUpdates.isEmpty())
      Database.update(shadowUpdates.values(), /* allOrNone */ false);
  }

  /*------------------------------------------------------------------
   *  finish
   *----------------------------------------------------------------*/
  public void finish(Database.BatchableContext ctx) {
    if (!programIds.isEmpty())
      System.enqueueJob(
        new AllineaProgrammaContinuationQueueable(programIds, notifyUserId)
      );
  }
}