force-app/main/default/objects/GiftTransaction/fields/Allocation_not_paid__c.field-meta.xml
<CustomField>
    <fullName>Allocation_not_paid__c</fullName>
    <label>Allocation Not Paid</label>
    <summaryFilterItems>
        <field>GiftTransactionDesignation.Status__c</field>
        <operation>notEqual</operation>
        <value>Paid</value>
    </summaryFilterItems>
    <summaryForeignKey>GiftTransactionDesignation.GiftTransactionId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Original_Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Donation_Amount__c</fullName>
    <formula>Donation__r.Original_Donation_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Donation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Donatore Anno</label>
    <referenceTo>Reporting_Year__c</referenceTo>
    <relationshipLabel>Donazioni</relationshipLabel>
    <relationshipName>Donazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Total_Allocations__c.field-meta.xml
<CustomField>
    <fullName>Total_Allocations__c</fullName>
    <label>Total Allocations</label>
    <summaryForeignKey>GiftTransactionDesignation.GiftTransactionId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Totale_Allocato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato__c</fullName>
    <label>Totale Allocato</label>
    <summarizedField>GiftTransactionDesignation.Amount</summarizedField>
    <summaryForeignKey>GiftTransactionDesignation.GiftTransactionId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Totale_Allocato_NON_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_NON_Pagato__c</fullName>
    <label>Totale Allocato NON Pagato</label>
    <summarizedField>GiftTransactionDesignation.Amount</summarizedField>
    <summaryFilterItems>
        <field>GiftTransactionDesignation.Status__c</field>
        <operation>notEqual</operation>
        <value>Paid</value>
    </summaryFilterItems>
    <summaryForeignKey>GiftTransactionDesignation.GiftTransactionId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Totale_Allocato_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_Pagato__c</fullName>
    <label>Totale Allocato Pagato</label>
    <summarizedField>GiftTransactionDesignation.Amount</summarizedField>
    <summaryFilterItems>
        <field>GiftTransactionDesignation.Status__c</field>
        <operation>equals</operation>
        <value>Paid</value>
    </summaryFilterItems>
    <summaryForeignKey>GiftTransactionDesignation.GiftTransactionId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/GiftTransaction/fields/Transazione_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Transazione_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transazione Shadow</label>
    <referenceTo>Transazione_Shadow__c</referenceTo>
    <relationshipLabel>Donation Transactions</relationshipLabel>
    <relationshipName>Donation_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Reporting_Year__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Donatori per Anno</relationshipLabel>
    <relationshipName>Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Totali_Donatore_Anno__c/Totali_Donatore_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Donatore Anno</label>
    <nameField>
        <label>Totali Donatore Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Donatore Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Totali_Donatore_Anno__c/fields/Totale_Allocato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato__c</fullName>
    <label>Totale Allocato</label>
    <summarizedField>Transazione_Shadow__c.Totale_Allocato_Static__c</summarizedField>
    <summaryForeignKey>Transazione_Shadow__c.Totali_Donatore_Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Totali_Donatore_Anno__c/fields/Totale_Allocato_NON_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_NON_Pagato__c</fullName>
    <label>Totale Allocato NON Pagato</label>
    <summarizedField>Transazione_Shadow__c.Totale_Allocato_NON_Pagato_Static__c</summarizedField>
    <summaryForeignKey>Transazione_Shadow__c.Totali_Donatore_Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Totali_Donatore_Anno__c/fields/Totale_Allocato_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_Pagato__c</fullName>
    <label>Totale Allocato Pagato</label>
    <summarizedField>Transazione_Shadow__c.Totale_Allocato_Pagato_Static__c</summarizedField>
    <summaryForeignKey>Transazione_Shadow__c.Totali_Donatore_Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transazione_Shadow__c/Transazione_Shadow__c.object-meta.xml
<CustomObject>
    <label>Transazione Shadow</label>
    <nameField>
        <label>Transazione Shadow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni Shadow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Transazione_Shadow__c/fields/Totale_Allocato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato__c</fullName>
    <formula>Transazione__r.Totale_Allocato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Allocato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Transazione_Shadow__c/fields/Totale_Allocato_NON_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_NON_Pagato__c</fullName>
    <formula>Transazione__r.Totale_Allocato_NON_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Allocato NON Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Transazione_Shadow__c/fields/Totale_Allocato_Pagato__c.field-meta.xml
<CustomField>
    <fullName>Totale_Allocato_Pagato__c</fullName>
    <formula>Transazione__r.Totale_Allocato_Pagato__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Allocato Pagato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Transazione_Shadow__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Transazioni Shadow</relationshipLabel>
    <relationshipName>Transazioni_Shadow</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Transazione_Shadow__c/fields/Transazione__c.field-meta.xml
<CustomField>
    <fullName>Transazione__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transazione</label>
    <referenceTo>GiftTransaction</referenceTo>
    <relationshipLabel>Transazioni Shadow</relationshipLabel>
    <relationshipName>Transazioni_Shadow</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateTransazioneShadowBatch.cls
/**
 * Batch per creare Transazione_Shadow__c una alla volta (batch size 1) per evitare
 * UNABLE_TO_LOCK_ROW su Totali_Donatore_Anno__c quando più transazioni condividono lo stesso parent.
 */
public class CreateTransazioneShadowBatch implements Database.Batchable<Id> {
    private List<Id> transactionIds;

    public CreateTransazioneShadowBatch(List<Id> transactionIds) {
        this.transactionIds = transactionIds != null ? transactionIds : new List<Id>();
    }

    public Iterable<Id> start(Database.BatchableContext bc) {
        return transactionIds;
    }

    public void execute(Database.BatchableContext bc, List<Id> scope) {
        if (scope.isEmpty()) return;
        Id txId = scope[0];
        List<GiftTransaction> txs = [
            SELECT Id, Name, Reporting_Year__c, Reporting_Year__r.Totali_Donatore_Anno__c,
                CurrentAmount, Allocation_not_paid__c, Original_Donation_Amount__c,
                Total_Allocations__c, Totale_Allocato__c, Totale_Allocato_NON_Pagato__c, Totale_Allocato_Pagato__c
            FROM GiftTransaction
            WHERE Id = :txId AND Transazione_Shadow__c = null
            LIMIT 1
        ];
        if (txs.isEmpty()) return;
        GiftTransaction tx = txs[0];
        Id totaliId = tx.Reporting_Year__r != null ? tx.Reporting_Year__r.Totali_Donatore_Anno__c : null;
        if (totaliId == null) return;
        Transazione_Shadow__c sh = new Transazione_Shadow__c(
            Name = tx.Name + ' - Shadow',
            Totali_Donatore_Anno__c = totaliId,
            Transazione__c = tx.Id
        );
        insert sh;
        GiftTransaction toUpdate = new GiftTransaction(Id = tx.Id, Transazione_Shadow__c = sh.Id);
        update toUpdate;
        UpdateTransazioneShadowStaticInvocable.processPayloadsSynchronously(new List<UpdateTransazioneShadowStaticQueueable.Payload>{
            new UpdateTransazioneShadowStaticQueueable.Payload(
                sh.Id, tx.CurrentAmount, tx.Allocation_not_paid__c != null ? tx.Allocation_not_paid__c.intValue() : null,
                tx.Original_Donation_Amount__c, tx.Total_Allocations__c != null ? tx.Total_Allocations__c.intValue() : null,
                tx.Totale_Allocato__c, tx.Totale_Allocato_NON_Pagato__c, tx.Totale_Allocato_Pagato__c
            )
        });
    }

    public void finish(Database.BatchableContext bc) { }
}