force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Grande Donatore</label>
</RecordType>

mdapi/objects/Anno_Reportistica__c/Anno_Reportistica__c.object-meta.xml
<CustomObject>
    <label>Anno Reportistica</label>
    <nameField>
        <label>Anno di Reportistica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anni Reportistica</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Comune__c/Comune__c.object-meta.xml
<CustomObject>
    <label>Comune</label>
    <nameField>
        <label>Comune Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comuni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Comune__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Province_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comune__c/fields/Regione__c.field-meta.xml
<CustomField>
    <fullName>Regione__c</fullName>
    <label>Regione</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/GiftDesignation/fields/DEFAULT_PRG__c.field-meta.xml
<CustomField>
    <fullName>DEFAULT_PRG__c</fullName>
    <formula>Partner__r.Default_per_Budgets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Default per Programma</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GiftDesignation/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GiftDesignation/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Fattura</label>
    <nameField>
        <displayFormat>Fattura-{00000000}</displayFormat>
        <label>Codice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fatture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Medical_Center__c.field-meta.xml
<CustomField>
    <fullName>Medical_Center__c</fullName>
    <label>Medical Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Non_Profit_Signaling__c.field-meta.xml
<CustomField>
    <fullName>Non_Profit_Signaling__c</fullName>
    <label>Non Profit Signaling</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Province_Global</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/Invoice__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Piccolo Donatore</label>
</RecordType>

force-app/main/default/objects/ProgramEnrollment/fields/Tipo_Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Stakeholder__c</fullName>
    <formula>Account.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo Stakeholder</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_Visita__c/Tipo_Visita__c.object-meta.xml
<CustomObject>
    <label>Tipo Visita</label>
    <nameField>
        <label>Tipo Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipi Visite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_Visita__c/fields/Tipo_Visita__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Visita__c</fullName>
    <label>Tipo Visita</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visita Medica</label>
    <nameField>
        <displayFormat>Visita-{00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visite Mediche</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Visit__c/fields/Beneficiary_Type__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary_Type__c</fullName>
    <label>Beneficiary Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minorenne</fullName>
            </value>
            <value>
                <fullName>Donna</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi/objects/Visit__c/fields/Data_della_Visita__c.field-meta.xml
<CustomField>
    <fullName>Data_della_Visita__c</fullName>
    <label>Data della Visita</label>
    <type>Date</type>
</CustomField>

mdapi/objects/Visit__c/fields/Duration_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_minutes__c</fullName>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Visit__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Visit__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Visit__c/fields/Tipo_Visita__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo Visita</label>
    <referenceTo>Tipo_Visita__c</referenceTo>
    <relationshipLabel>Visite Mediche</relationshipLabel>
    <relationshipName>Visite_Mediche</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Visit__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Province_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agrigento (AG)</fullName>
    </customValue>
    <customValue>
        <fullName>Alessandria (AL)</fullName>
    </customValue>
    <customValue>
        <fullName>Ancona (AN)</fullName>
    </customValue>
    <customValue>
        <fullName>Aosta (AO)</fullName>
    </customValue>
    <customValue>
        <fullName>Arezzo (AR)</fullName>
    </customValue>
    <customValue>
        <fullName>Ascoli Piceno (AP)</fullName>
    </customValue>
    <customValue>
        <fullName>Asti (AT)</fullName>
    </customValue>
    <customValue>
        <fullName>Avellino (AV)</fullName>
    </customValue>
    <customValue>
        <fullName>Bari (BA)</fullName>
    </customValue>
    <customValue>
        <fullName>Barletta-Andria-Trani (BT)</fullName>
    </customValue>
    <customValue>
        <fullName>Belluno (BL)</fullName>
    </customValue>
    <customValue>
        <fullName>Benevento (BN)</fullName>
    </customValue>
    <customValue>
        <fullName>Bergamo (BG)</fullName>
    </customValue>
    <customValue>
        <fullName>Biella (BI)</fullName>
    </customValue>
    <customValue>
        <fullName>Bologna (BO)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolzano/Bozen (BZ)</fullName>
    </customValue>
    <customValue>
        <fullName>Brescia (BS)</fullName>
    </customValue>
    <customValue>
        <fullName>Brindisi (BR)</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliari (CA)</fullName>
    </customValue>
    <customValue>
        <fullName>Caltanissetta (CL)</fullName>
    </customValue>
    <customValue>
        <fullName>Campobasso (CB)</fullName>
    </customValue>
    <customValue>
        <fullName>Caserta (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>Catania (CT)</fullName>
    </customValue>
    <customValue>
        <fullName>Catanzaro (CZ)</fullName>
    </customValue>
    <customValue>
        <fullName>Chieti (CH)</fullName>
    </customValue>
    <customValue>
        <fullName>Como (CO)</fullName>
    </customValue>
    <customValue>
        <fullName>Cosenza (CS)</fullName>
    </customValue>
    <customValue>
        <fullName>Cremona (CR)</fullName>
    </customValue>
    <customValue>
        <fullName>Crotone (KR)</fullName>
    </customValue>
    <customValue>
        <fullName>Cuneo (CN)</fullName>
    </customValue>
    <masterLabel>Province</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/Region_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abruzzo</fullName>
    </customValue>
    <customValue>
        <fullName>Basilicata</fullName>
    </customValue>
    <customValue>
        <fullName>Calabria</fullName>
    </customValue>
    <customValue>
        <fullName>Campania</fullName>
    </customValue>
    <customValue>
        <fullName>Emilia-Romagna</fullName>
    </customValue>
    <customValue>
        <fullName>Friuli-Venezia Giulia</fullName>
    </customValue>
    <customValue>
        <fullName>Lazio</fullName>
    </customValue>
    <customValue>
        <fullName>Liguria</fullName>
    </customValue>
    <customValue>
        <fullName>Lombardia</fullName>
    </customValue>
    <customValue>
        <fullName>Marche</fullName>
    </customValue>
    <customValue>
        <fullName>Molise</fullName>
    </customValue>
    <customValue>
        <fullName>Piemonte</fullName>
    </customValue>
    <customValue>
        <fullName>Puglia</fullName>
    </customValue>
    <customValue>
        <fullName>Sardegna</fullName>
    </customValue>
    <customValue>
        <fullName>Sicilia</fullName>
    </customValue>
    <customValue>
        <fullName>Toscana</fullName>
    </customValue>
    <customValue>
        <fullName>Trentino-Alto Adige</fullName>
    </customValue>
    <customValue>
        <fullName>Umbria</fullName>
    </customValue>
    <customValue>
        <fullName>Valle d&apos;Aosta</fullName>
    </customValue>
    <customValue>
        <fullName>Veneto</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

mdapi/classes/VisiteMediche.cls
public with sharing class VisiteMediche {
  private static final String TEMPO_SOSPESO = 'Tempo Sospeso';
  @AuraEnabled(cacheable=true)
  public static BudgetWrapper getBudgetId() {
    /* 1️⃣  Recupero la CompanyName dell’utente */
    User u = [
      SELECT CompanyName
      FROM User
      WHERE Id = :UserInfo.getUserId()
      LIMIT 1
    ];
    if (String.isBlank(u.CompanyName)) {
      return null; // → niente CompanyName ⇒ niente budget
    }

    /* 2️⃣  Account corrispondente alla CompanyName */
    List<Account> accs = [
      SELECT Id
      FROM Account
      WHERE Name = :u.CompanyName
      LIMIT 1
    ];
    if (accs.isEmpty()) {
      return null; // → l’utente non è legato a un Account
    }
    Id accId = accs[0].Id;

    /* 3️⃣  GiftDesignation collegata all’Account sul programma “Tempo Sospeso” */
    List<GiftDesignation> gds = [
      SELECT Id, Name, DEFAULT_PRG__c
      FROM GiftDesignation
      WHERE Partner__c = :accId AND Program__r.Name = :TEMPO_SOSPESO
      LIMIT 1
    ];
    if (gds.isEmpty()) {
      return null; // → nessun budget trovato
    }

    GiftDesignation gd = gds[0];
    Boolean isDefault = gd.DEFAULT_PRG__c == null ? false : gd.DEFAULT_PRG__c;
    return new BudgetWrapper(gd.Id, gd.Name, isDefault);
  }

  @AuraEnabled(cacheable=true)
  public static Map<String, Object> getRelatedRecords(
    String year,
    String tipoVisita,
    String month,
    String beneficiario,
    String invoiceNumber,
    String budgetId,
    String donorId,
    Integer limitSize,
    Integer offsetSize,
    String city,
    String province,
    String region
  ) {
    Boolean hasBudgetFilter = !String.isBlank(budgetId);

    String baseQuery =
      'SELECT Id, Name, Beneficiary_Type__c, Duration_in_minutes__c, ' +
      'Quantity__c, Invoice__c, Invoice__r.Name, Invoice__r.Invoice_Number__c, ' +
      'Invoice__r.Budget__c, Invoice__r.Budget__r.Name, ' +
      'Invoice__r.Account__c, Invoice__r.Account__r.Name, ' +
      'Tipo_Visita__c, Tipo_Visita__r.Id, Tipo_Visita__r.Name, ' +
      'Amount__c, Data_della_Visita__c, City__c, Province__c, Region__c ' +
      'FROM Visit__c';

    List<String> conditions = new List<String>();

    if (hasBudgetFilter) {
      conditions.add(
        'Invoice__r.Budget__c = \'' + String.escapeSingleQuotes(budgetId) + '\''
      );
    }
    if (!String.isBlank(year)) {
      conditions.add(
        'CALENDAR_YEAR(Data_della_Visita__c) = ' +
        String.escapeSingleQuotes(year)
      );
    }

    if (!String.isBlank(tipoVisita)) {
      List<String> tipi = tipoVisita.split(',');
      List<String> condTipo = new List<String>();
      for (String t : tipi) {
        condTipo.add(
          'Tipo_Visita__r.Name = \'' +
            String.escapeSingleQuotes(t.trim()) +
            '\''
        );
      }
      conditions.add('(' + String.join(condTipo, ' OR ') + ')');
    }

    if (!String.isBlank(month)) {
      conditions.add(
        'CALENDAR_MONTH(Data_della_Visita__c) = ' +
        String.escapeSingleQuotes(month)
      );
    }

    if (!String.isBlank(beneficiario)) {
      conditions.add(
        'Beneficiary_Type__c = \'' +
          String.escapeSingleQuotes(beneficiario) +
          '\''
      );
    }

    if (!String.isEmpty(invoiceNumber)) {
      String likeValue = '%' + invoiceNumber + '%';
      conditions.add(
        'Invoice__r.Invoice_Number__c LIKE \'' +
          String.escapeSingleQuotes(likeValue) +
          '\''
      );
    }

    if (!String.isBlank(donorId)) {
      conditions.add(
        'Invoice__r.Account__c = \'' + String.escapeSingleQuotes(donorId) + '\''
      );
    }

    if (!String.isBlank(city)) {
      conditions.add('City__c = \'' + String.escapeSingleQuotes(city) + '\'');
    }
    if (!String.isBlank(province)) {
      conditions.add(
        'Province__c = \'' + String.escapeSingleQuotes(province) + '\''
      );
    }
    if (!String.isBlank(region)) {
      conditions.add(
        'Region__c = \'' + String.escapeSingleQuotes(region) + '\''
      );
    }

    String whereClause = conditions.isEmpty()
      ? ''
      : ' WHERE ' + String.join(conditions, ' AND ');

    /* --- 2. Query di aggregazione SENZA LIMIT/OFFSET --------------- */
    String aggQuery =
      'SELECT ' +
      '  SUM(Duration_in_minutes__c)    totMinutes, ' +
      '  SUM(Quantity__c)               totVisits,  ' +
      '  SUM(Amount__c)                 totAmount   ' +
      'FROM Visit__c' +
      whereClause;

    AggregateResult ar = Database.query(aggQuery);
    Decimal totalMinutes = (Decimal) ar.get('totMinutes');
    Decimal totalVisits = (Decimal) ar.get('totVisits');
    Decimal totalAmount = (Decimal) ar.get('totAmount');

    String fullQuery =
      baseQuery +
      whereClause +
      ' ORDER BY Data_della_Visita__c DESC' +
      ' LIMIT ' +
      limitSize +
      ' OFFSET ' +
      offsetSize;

    System.debug('SOQL VISITE: ' + fullQuery);

    List<Visit__c> records = Database.query(fullQuery);

    return new Map<String, Object>{
      'records' => records,
      'totalMinutes' => totalMinutes != null ? totalMinutes : 0,
      'totalVisits' => totalVisits != null ? totalVisits : 0,
      'totalAmount' => totalAmount != null ? totalAmount : 0,
      'query' => fullQuery,
      'aggQuery' => aggQuery
    };
  }

  @AuraEnabled(cacheable=true)
  public static List<String> getBeneficiaryTypes() {
    List<String> options = new List<String>();
    Schema.DescribeFieldResult fieldDesc = Visit__c.Beneficiary_Type__c.getDescribe();
    for (Schema.PicklistEntry entry : fieldDesc.getPicklistValues()) {
      options.add(entry.getValue());
    }
    return options;
  }

  @AuraEnabled(cacheable=true)
  public static List<String> getAvailableYears() {
    List<AggregateResult> agg = [
      SELECT Name
      FROM Anno_Reportistica__c
      GROUP BY Name
      ORDER BY Name
    ];

    List<String> years = new List<String>();
    for (AggregateResult ar : agg) {
      years.add((String) ar.get('Name'));
    }
    return years;
  }

  @AuraEnabled(cacheable=true)
  public static List<IdLabelPair> getAvailableBudgets() {
    List<GiftDesignation> budgets = [
      SELECT Id, Name
      FROM GiftDesignation
      WHERE Program__r.Name = :TEMPO_SOSPESO // 👈 filtro sul programma
      ORDER BY Name
    ];
    List<IdLabelPair> options = new List<IdLabelPair>();
    for (GiftDesignation b : budgets) {
      options.add(new IdLabelPair(b.Id, b.Name));
    }
    return options;
  }

  public virtual class IdLabelPair {
    @AuraEnabled
    public String label { get; set; }
    @AuraEnabled
    public String value { get; set; }
    public IdLabelPair(String value, String label) {
      this.label = label;
      this.value = value;
    }
  }

  public class BudgetWrapper extends IdLabelPair {
    @AuraEnabled
    public Boolean isDefault;
    public BudgetWrapper(String id, String name, Boolean isDefault) {
      super(id, name);
      this.isDefault = isDefault;
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Tipo_Visita__c> getTipiVisita() {
    return [SELECT Id, Name FROM Tipo_Visita__c ORDER BY Name];
  }

  // AGGIUNGI (o riutilizza) un metodo getAllComuni()
  // (Se non lo hai già, puoi replicare quello usato in Fatture)
  @AuraEnabled(cacheable=true)
  public static List<ComuneWrapper> getAllComuni() {
    List<Comune__c> comuni = [
      SELECT Id, Name, Provincia__c, Regione__c
      FROM Comune__c
      ORDER BY Name
    ];
    List<ComuneWrapper> result = new List<ComuneWrapper>();
    for (Comune__c c : comuni) {
      result.add(new ComuneWrapper(c.Id, c.Name, c.Provincia__c, c.Regione__c));
    }
    return result;
  }

  /**
   * Restituisce l'elenco (deduplicato) delle combinazioni città/provincia/regione
   * presenti sui record Visit__c, per permettere filtri coerenti anche su Experience Cloud.
   */
  @AuraEnabled(cacheable=true)
  public static List<ComuneWrapper> getVisitLocations() {
    List<AggregateResult> groups = [
      SELECT City__c, Province__c, Region__c
      FROM Visit__c
      WHERE City__c != NULL OR Province__c != NULL OR Region__c != NULL
      GROUP BY City__c, Province__c, Region__c
      ORDER BY City__c, Province__c, Region__c
    ];

    List<ComuneWrapper> result = new List<ComuneWrapper>();
    for (AggregateResult aggr : groups) {
      String city = (String) aggr.get('City__c');
      String province = (String) aggr.get('Province__c');
      String region = (String) aggr.get('Region__c');
      String key = String.join(
        new List<String>{
          city == null ? '' : city,
          province == null ? '' : province,
          region == null ? '' : region
        },
        '|'
      );
      result.add(new ComuneWrapper(key, city, province, region));
    }
    return result;
  }

  /**
   * Donatori filtrati per ProgramEnrollment e finestra temporale.
   * - programId: opzionale; se null usa Program con Name = 'Tempo Sospeso'
   * - year: se blank → considera solo enrollment attivi (IsActive=TRUE) in qualunque data
   * - month: se blank → applica solo il filtro anno (attivo almeno un giorno nell'anno)
   *          altrimenti attivo almeno un giorno nel mese specificato
   */
  @AuraEnabled(cacheable=true)
  public static List<Fatture.IdNameWrapper> getAvailableDonors(
    String year,
    String month,
    Id programId
  ) {
    Id prgId = programId;
    if (prgId == null) {
      List<Program> ps = [
        SELECT Id
        FROM Program
        WHERE Name = :TEMPO_SOSPESO
        LIMIT 1
      ];
      if (!ps.isEmpty()) {
        prgId = ps[0].Id;
      }
    }

    Set<Id> accIds = new Set<Id>();

    if (String.isBlank(year)) {
      // Nessun filtro anno/mese → enrollment attivi in qualunque data
      String baseQuery = 'SELECT AccountId FROM ProgramEnrollment WHERE AccountId != NULL AND IsActive = TRUE';
      if (prgId != null) {
        baseQuery += ' AND ProgramId = :prgId';
      }
      baseQuery += ' AND (Tipo_Stakeholder__c = \'Grande Donatore\' OR Tipo_Stakeholder__c = \'Piccolo Donatore\')';

      List<ProgramEnrollment> enrollments = Database.query(baseQuery);
      if (enrollments.isEmpty()) {
        // In alcuni org il campo Tipo_Stakeholder__c è read-only: fallback senza filtro
        String fallbackQuery = 'SELECT AccountId FROM ProgramEnrollment WHERE AccountId != NULL AND IsActive = TRUE';
        if (prgId != null) {
          fallbackQuery += ' AND ProgramId = :prgId';
        }
        enrollments = Database.query(fallbackQuery);
      }
      for (ProgramEnrollment pe : enrollments)
        accIds.add(pe.AccountId);
    } else {
      Integer y = Integer.valueOf(year);
      Integer mStart = String.isBlank(month) ? 1 : Integer.valueOf(month);
      Integer mEnd = String.isBlank(month) ? 12 : Integer.valueOf(month);
      Date periodStart = Date.newInstance(y, mStart, 1);
      Date periodEnd = Date.newInstance(y, mEnd, Date.daysInMonth(y, mEnd));

      // Overlap logica: StartDate <= periodEnd AND (EndDate == NULL OR EndDate >= periodStart)
      String baseQuery =
        'SELECT AccountId, StartDate, EndDate FROM ProgramEnrollment WHERE AccountId != NULL' +
        ' AND StartDate <= :periodEnd AND (EndDate = NULL OR EndDate >= :periodStart)';
      if (prgId != null) {
        baseQuery += ' AND ProgramId = :prgId';
      }
      baseQuery += ' AND (Tipo_Stakeholder__c = \'Grande Donatore\' OR Tipo_Stakeholder__c = \'Piccolo Donatore\')';

      List<ProgramEnrollment> enrollments = Database.query(baseQuery);
      if (enrollments.isEmpty()) {
        String fallbackQuery =
          'SELECT AccountId, StartDate, EndDate FROM ProgramEnrollment WHERE AccountId != NULL' +
          ' AND StartDate <= :periodEnd AND (EndDate = NULL OR EndDate >= :periodStart)';
        if (prgId != null) {
          fallbackQuery += ' AND ProgramId = :prgId';
        }
        enrollments = Database.query(fallbackQuery);
      }
      for (ProgramEnrollment pe : enrollments)
        accIds.add(pe.AccountId);
    }

    if (accIds.isEmpty())
      return new List<Fatture.IdNameWrapper>();

    // Preleva IsPersonAccount per mappare lo Stakeholder Type: Company / PersonAccount
    List<Account> accs = [
      SELECT Id, Name, IsPersonAccount
      FROM Account
      WHERE Id IN :accIds
      ORDER BY Name
    ];

    // Filtro coerente con richiesta: Stakeholder Type ∈ { Company, PersonAccount }
    // (Qui derivato da IsPersonAccount: true → PersonAccount, false → Company)
    List<Fatture.IdNameWrapper> out = new List<Fatture.IdNameWrapper>();
    for (Account a : accs) {
      // Sempre vero per Account standard: includiamo solo Company/PersonAccount
      // (Non esistono altri tipi derivati da IsPersonAccount)
      out.add(new Fatture.IdNameWrapper(a.Id, a.Name));
    }
    return out;
  }

  public class ComuneWrapper {
    @AuraEnabled
    public String id { get; set; }
    @AuraEnabled
    public String name { get; set; }
    @AuraEnabled
    public String province { get; set; }
    @AuraEnabled
    public String region { get; set; }

    public ComuneWrapper(
      String id,
      String name,
      String province,
      String region
    ) {
      this.id = id;
      this.name = name;
      this.province = province;
      this.region = region;
    }
  }

  @AuraEnabled(cacheable=true)
  public static Map<String, Object> getVisitWithInvoiceData(
    String year,
    String month,
    String beneficiario,
    String budgetId,
    Integer limitSize,
    Integer offsetSize,
    String city,
    String province,
    String region
  ) {
    List<String> filters = new List<String>();

    if (!String.isBlank(year)) {
      filters.add(
        'CALENDAR_YEAR(Data_della_Visita__c) = ' +
        String.escapeSingleQuotes(year)
      );
    }
    if (!String.isBlank(month)) {
      filters.add(
        'CALENDAR_MONTH(Data_della_Visita__c) = ' +
        String.escapeSingleQuotes(month)
      );
    }
    if (!String.isBlank(beneficiario)) {
      filters.add(
        'Beneficiary_Type__c = \'' +
          String.escapeSingleQuotes(beneficiario) +
          '\''
      );
    }
    if (!String.isBlank(budgetId)) {
      filters.add(
        'Invoice__r.Budget__c = \'' + String.escapeSingleQuotes(budgetId) + '\''
      );
    }

    if (!String.isBlank(city)) {
      filters.add('City__c = \'' + String.escapeSingleQuotes(city) + '\'');
    }
    if (!String.isBlank(province)) {
      filters.add(
        'Province__c = \'' + String.escapeSingleQuotes(province) + '\''
      );
    }
    if (!String.isBlank(region)) {
      filters.add('Region__c = \'' + String.escapeSingleQuotes(region) + '\'');
    }

    String whereClause = filters.isEmpty()
      ? ''
      : ' WHERE ' + String.join(filters, ' AND ');

    // Aggregati completi sui risultati filtrati (indipendenti da LIMIT/OFFSET)
    String aggQuery =
      'SELECT ' +
      '  SUM(Quantity__c) totVisits, ' +
      '  SUM(Amount__c)   totAmount ' +
      'FROM Visit__c' +
      whereClause;

    AggregateResult ar = Database.query(aggQuery);
    Decimal totalVisits = (Decimal) ar.get('totVisits');
    Decimal totalAmount = (Decimal) ar.get('totAmount');

    String query =
      'SELECT Id, Visit_Type__c, Quantity__c, Beneficiary_Type__c, Duration_in_minutes__c, Amount__c, Data_della_Visita__c,' +
      ' Invoice__r.Id, Invoice__r.Account__c, Invoice__r.Account__r.Name, ' +
      ' Invoice__r.Budget__c, Invoice__r.Budget__r.Name, ' +
      ' Invoice__r.Medical_Center__c, Invoice__r.Invoice_Number__c, ' +
      ' Invoice__r.Date__c, Invoice__r.Non_Profit_Signaling__c, City__c, Province__c, Region__c ' +
      'FROM Visit__c' +
      whereClause +
      ' ORDER BY Invoice__r.Date__c DESC ' +
      ' LIMIT ' +
      limitSize +
      ' OFFSET ' +
      offsetSize;

    List<Visit__c> visits = Database.query(query);

    return new Map<String, Object>{
      'records' => visits,
      'query' => query,
      'totalVisits' => totalVisits != null ? totalVisits : 0,
      'totalAmount' => totalAmount != null ? totalAmount : 0
    };
  }
}