force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Structure.recordType-meta.xml
<RecordType>
    <fullName>Structure</fullName>
    <active>true</active>
    <label>Fornitore</label>
</RecordType>

force-app/main/default/objects/GiftDesignation/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>Pagamento-{00000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Payment__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Payment__c/fields/Data_di_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Data_di_Pagamento__c</fullName>
    <label>Data di Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <label>Spettacolo</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Show__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <label>Data e Ora</label>
    <type>DateTime</type>
</CustomField>

mdapi/objects/Show__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Struttura</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows</relationshipLabel>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/TicketAvailability__c/TicketAvailability__c.object-meta.xml
<CustomObject>
    <label>Offerta</label>
    <nameField>
        <displayFormat>Offerta-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offerte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/TicketAvailability__c/fields/NumberUses__c.field-meta.xml
<CustomField>
    <fullName>NumberUses__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Numero Utilizzi</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/OfferExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpirationDate__c</fullName>
    <label>Data Scadenza Offerta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PartnerTicketAvailabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Show__c.field-meta.xml
<CustomField>
    <fullName>Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spettacolo</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipName>Biglietti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Stato</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponibile</fullName>
                <default>true</default>
                <label>Disponibile</label>
            </value>
            <value>
                <fullName>Prenotato</fullName>
            </value>
            <value>
                <fullName>Utilizzato</fullName>
            </value>
            <value>
                <fullName>Scaduto</fullName>
            </value>
            <value>
                <fullName>Fatturato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornitore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offerte (Struttura)</relationshipLabel>
    <relationshipName>TicketAvailabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <label>Nome Abbonamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/TicketType__c.field-meta.xml
<CustomField>
    <fullName>TicketType__c</fullName>
    <label>Tipologia Offerta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TicketType</valueSetName>
    </valueSet>
</CustomField>

mdapi/globalValueSets/TicketType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biglietto</fullName>
    </customValue>
    <customValue>
        <fullName>Abbonamento</fullName>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>Biglietti Multipli</fullName>
        <isActive>false</isActive>
        <label>Biglietti Multipli</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <masterLabel>Tipologia Biglietto</masterLabel>
</GlobalValueSet>

mdapi/classes/EmailController.cls
/**
 * @description       : Email Controller
 * @author            : Seidor
**/
public without sharing class EmailController {

    private static final String TYPE_INSERT = 'insert';
    private static final String TYPE_BUY = 'buy';
    private static final String TYPE_UPDATE = 'update';
    private static final String TYPE_PAYMENT = 'payment';
    private static final String TEMPLATE_BUY = 'BuyTicket';
    private static final String TEMPLATE_INSERT = 'InsertTicket';
    private static final String TEMPLATE_UPDATE = 'UpdateTicket';
    private static final String TEMPLATE_PAYMENT = 'Payment';

    /**
    * @description Generate Structure code
    * @return String 
    **/
    @InvocableMethod(label='Invia Email')
    public static void sendEmails(List<FlowInput> inputs) {
        List<TicketAvailability__c> insertInput = new List<TicketAvailability__c>();
        List<TicketAvailability__c> buyInput = new List<TicketAvailability__c>();
        List<TicketAvailability__c> updateInput = new List<TicketAvailability__c>();
        List<Payment__c> paymentInput = new List<Payment__c>();

        try {
            for (FlowInput input : inputs) {
                if (input.type.equals(TYPE_INSERT)) {
                    insertInput.addAll(input.tickets);
                } else if (input.type.equals(TYPE_BUY)) {
                    buyInput.addAll(input.tickets);
                } else if (input.type.equals(TYPE_UPDATE)) {
                    updateInput.addAll(input.tickets);
                } else if (input.type.equals(TYPE_PAYMENT)) {
                    paymentInput.addAll(input.payments);
                }
            }
    
            if (!insertInput.isEmpty()) { sendInsertEmails(insertInput); }
            if (!buyInput.isEmpty()) { sendBuyEmails(buyInput); }
            if (!updateInput.isEmpty()) { sendUpdateEmails(updateInput); }
            if (!paymentInput.isEmpty()) { sendPaymentEmails(paymentInput); }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, '[EmailController]::[sendEmails]::[Message]: ' + e.getMessage());
            System.debug(LoggingLevel.ERROR, '[EmailController]::[sendEmails]::[Stack]: ' + e.getStackTraceString());
        }
    }

    public class FlowInput {
        @InvocableVariable(label='Tipologia' description='Valori accettati: insert, buy, update, payment' required=true)
        public String type;

        @InvocableVariable(label='Offerte' description='Lista di TicketAvailability__c - Obbligatorio per tipologia: insert, buy, update')
        public List<TicketAvailability__c> tickets;

        @InvocableVariable(label='Pagamenti' description='Lista di Pagamenti - Obbligatorio per tipologia: payment')
        public List<Payment__c> payments;
    }

    /**
    * @description Send insert emails
    * @param tickets : List<TicketAvailability__c>
    **/
    private static void sendInsertEmails(List<TicketAvailability__c> tickets) {
        Set<Id> ticketIds = new Set<Id>();

        for (TicketAvailability__c ticket : tickets) {
            ticketIds.add(ticket.Id);
        }

        tickets = getTickets(ticketIds);

        EmailTemplate template = getEmailTemplate(TEMPLATE_INSERT);
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        List<ProgramEnrollment> partners = getPartners();
        String baseUrl = getBaseUrl();

        for (User user : getUsers(partners)) {
            if (String.isNotBlank(user.Email)) {
                for (TicketAvailability__c ticket : tickets) {
                    Messaging.SingleEmailMessage email = new  Messaging.SingleEmailMessage();
                    String body = template.HtmlValue;

                    String type = ticket.TicketType__c.equals('Biglietto') ? 'bigliett' : 'abbonament';
                    type += ticket.NumberUses__c > 1 ? 'i ' : 'o ';
                    type += ticket.TicketType__c.equals('Biglietto') ? ('per ' + ticket.Show__r.Name + ' del ' + ticket.Show__r.Datetime__c.format()) : (String.isNotBlank(ticket.SubscriptionName__c) ? ticket.SubscriptionName__c : '');
                    type += ' con codice ' + ticket.Name;

                    body = body.replace('{{partner}}', user.CompanyName)
                               .replace('{{quantity}}', String.valueOf(ticket.NumberUses__c))
                               .replace('{{type}}', type)
                               .replace('{{structure}}', ticket.Structure__r.Name)
                               .replace('{{expireDate}}', ticket.OfferExpirationDate__c.format())
                               .replace('{{baseUrl}}', baseUrl);
                    
                    email.setOrgWideEmailAddressId(getOrgWideEmailAddressId());
                    email.setToAddresses(new String[]{user.Email});
                    email.setSubject(template.Subject);
                    email.setHtmlBody(body);

                    emails.add(email);
                }
            }
        }

        if(!Test.isRunningTest()) { Messaging.sendEmail(emails); }
    }

    /**
    * @description Send buy emails
    * @param tickets : List<TicketAvailability__c>
    **/
    private static void sendBuyEmails(List<TicketAvailability__c> tickets) {
        Set<Id> ticketIds = new Set<Id>();

        for (TicketAvailability__c ticket : tickets) {
            ticketIds.add(ticket.Id);
        }

        tickets = getTickets(ticketIds);

        EmailTemplate template = getEmailTemplate(TEMPLATE_BUY);
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for (TicketAvailability__c ticket : tickets) {
            Messaging.SingleEmailMessage email = new  Messaging.SingleEmailMessage();
            String body = template.HtmlValue;

            body = body.replace('{{structure}}', ticket.Structure__r.Name)
                       .replace('{{ticketType}}',ticket.TicketType__c)
                       .replace('{{offerType}}', ticket.State__c)
                       .replace('{{ticketName}}', ticket.Name)
                       .replace('{{partner}}', ticket.Partner__r.Name)
                       .replace('{{phone}}', ticket.Partner__r.Phone)
                       .replace('{{email}}', ticket.Partner__r.Email__c)
                       .replace('{{other}}', ticket.State__c.equals('Prenotato') ? '<p>Si prega di contattare l\'ente per finalizzare la prenotazione e/o il pagamento.</p>' : '');
            
            email.setOrgWideEmailAddressId(getOrgWideEmailAddressId());
            email.setToAddresses(new String[]{ticket.Structure__r.Email__c});
            email.setSubject(template.Subject);
            email.setHtmlBody(body);

            emails.add(email);
        }

        if(!Test.isRunningTest()) { Messaging.sendEmail(emails); }
    }

    /**
    * @description Send update emails
    * @param tickets : List<TicketAvailability__c>
    **/
    private static void sendUpdateEmails(List<TicketAvailability__c> tickets) {
        Set<Id> ticketIds = new Set<Id>();

        for (TicketAvailability__c ticket : tickets) {
            ticketIds.add(ticket.Id);
        }

        tickets = getTickets(ticketIds);

        EmailTemplate template = getEmailTemplate(TEMPLATE_UPDATE);
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        List<ProgramEnrollment> partners = getPartners();
        String baseUrl = getBaseUrl();

        for (User user : getUsers(partners)) {
            if (String.isNotBlank(user.Email)) {
                for (TicketAvailability__c ticket : tickets) {
                    Messaging.SingleEmailMessage email = new  Messaging.SingleEmailMessage();
                    String body = template.HtmlValue;

                    body = body.replace('{{partner}}', user.CompanyName)
                               .replace('{{desc}}', ticket.Name)
                               .replace('{{structure}}', ticket.Structure__r.Name)
                               .replace('{{baseUrl}}', baseUrl);
                    
                    email.setOrgWideEmailAddressId(getOrgWideEmailAddressId());
                    email.setToAddresses(new String[]{user.Email});
                    email.setSubject(template.Subject);
                    email.setHtmlBody(body);

                    emails.add(email);
                }
            }
        }

        if(!Test.isRunningTest()) { Messaging.sendEmail(emails); }
    }

    /**
    * @description Send payment emails
    * @param payments : List<Payment__c>
    **/
    private static void sendPaymentEmails(List<Payment__c> payments) {
        Set<Id> paymentIds = new Set<Id>();

        for (Payment__c payment : payments) {
            paymentIds.add(payment.Id);
        }

        payments = getPayments(paymentIds);

        if (payments.isEmpty()) { return; }

        Set<String> partners = new Set<String>();
        for (Payment__c payment : payments) {
            if (payment.Budget__r != null && payment.Budget__r.Partner__r != null) {
                partners.add(payment.Budget__r.Partner__r.Name);
            }
        }
        
        Map<String,User> users = new Map<String,User>();
        for (User user : getUsers(partners)) {
            users.put(user.CompanyName, user);
        }

        EmailTemplate template = getEmailTemplate(TEMPLATE_PAYMENT);
        if (template == null) {
            System.debug(LoggingLevel.ERROR, '[EmailController] Missing EmailTemplate with DeveloperName=' + TEMPLATE_PAYMENT);
            return;
        }
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        String baseUrl = getBaseUrl();
        
        for (Payment__c payment : payments) {
            Messaging.SingleEmailMessage email = new  Messaging.SingleEmailMessage();
            String body = template.HtmlValue;

            // Resolve recipient and partner name with fallbacks
            String partnerName = (payment.Budget__r != null && payment.Budget__r.Partner__r != null)
                ? payment.Budget__r.Partner__r.Name : null;
            User user = (partnerName != null) ? users.get(partnerName) : null;
            String toAddress = (user != null && String.isNotBlank(user.Email))
                ? user.Email
                : ((payment.Budget__r != null && payment.Budget__r.Partner__r != null)
                    ? payment.Budget__r.Partner__r.Email__c
                    : null);

            if (String.isBlank(partnerName) || String.isBlank(toAddress)) {
                System.debug(LoggingLevel.WARN, '[EmailController] Skipping payment email due to missing partner/to: paymentId=' + payment.Id);
                continue;
            }

            String dateStr = (payment.Data_di_Pagamento__c != null)
                ? payment.Data_di_Pagamento__c.format()
                : Date.today().format();

            body = body.replace('{{partner}}', partnerName)
                        .replace('{{date}}', dateStr)
                        .replace('{{amount}}', String.valueOf(payment.Amount__c));
            
            Id orgWideId = getOrgWideEmailAddressId();
            if (orgWideId != null) {
                email.setOrgWideEmailAddressId(orgWideId);
            }
            email.setToAddresses(new String[]{toAddress});
            email.setSubject(template.Subject);
            email.setHtmlBody(body);

            emails.add(email);
        }

        if(!Test.isRunningTest()) { Messaging.sendEmail(emails); }
    }

    /**
    * @description Get Users
    * @param partners : List<ProgramEnrollment>
    * @return List<User>
    **/
    private static List<User> getUsers(List<ProgramEnrollment> partners){
        Set<String> names = new Set<String>();

        for (ProgramEnrollment partner : partners) {
            names.add(partner.Account.Name);
        }

        return getUsers(names);
    }

    /**
    * @description Get email template from specific name 
    * @param emailTemplateName : String 
    * @return EmailTemplate 
    **/
    private static EmailTemplate getEmailTemplate(String emailTemplateName){
        List<EmailTemplate> ts = [SELECT Id, HtmlValue, Body, Subject 
                                     FROM EmailTemplate 
                                    WHERE DeveloperName = :emailTemplateName 
                                     WITH SYSTEM_MODE 
                                    LIMIT 1];
        return ts.isEmpty() ? null : ts[0];
    }

    /**
    * @description Get tickets
    * @param ticketIds : Set<Id>
    * @return List<TicketAvailability__c> 
    **/
    private static List<TicketAvailability__c> getTickets(Set<Id> ticketIds){
        return [SELECT Id, Name, TicketType__c, State__c, Structure__r.Name, Structure__r.Email__c, Partner__r.Name, 
                       NumberUses__c, Show__r.Name, Show__r.Datetime__c, SubscriptionName__c, Partner__r.Email__c, Partner__r.Phone, OfferExpirationDate__c
                  FROM TicketAvailability__c 
                 WHERE Id IN :ticketIds 
                  WITH SYSTEM_MODE];
    }

    /**
    * @description Get payments
    * @param paymentIds : Set<Id>
    * @return List<Payment__c> 
    **/
    private static List<Payment__c> getPayments(Set<Id> paymentIds){
        return [SELECT Id, Amount__c, Data_di_Pagamento__c, Budget__r.Partner__r.Name, Budget__r.Partner__r.Email__c
                  FROM Payment__c 
                 WHERE Id IN :paymentIds 
                  WITH SYSTEM_MODE];
    }

    /**
    * @description Get Partners
    * @return List<ProgramEnrollment>
    **/
    private static List<ProgramEnrollment> getPartners(){
        return [SELECT Account.Name 
                  FROM ProgramEnrollment 
                 WHERE Program.Name = :ProgramEnrollmentService.SORRISO_SOSPESO
                   AND Account.RecordType.DeveloperName = 'Partner' 
                  WITH SYSTEM_MODE];
    }

    /**
    * @description Get users
    * @param names : Set<String>
    * @return List<User> 
    **/
    private static List<User> getUsers(Set<String> names){
        return [SELECT CompanyName, Email FROM User WHERE CompanyName IN :names WITH SYSTEM_MODE];
    }

    /**
    * @description Get OrgWideEmailAddress Id
    * @return Id 
    **/
    private static Id getOrgWideEmailAddressId() {
        List<OrgWideEmailAddress> ow = [SELECT Id FROM OrgWideEmailAddress WITH SYSTEM_MODE LIMIT 1];
        return ow.isEmpty() ? null : ow[0].Id;
    }

    /**
    * @description Get base url
    * @return String 
    **/
    private static String getBaseUrl(){
        return URL.getOrgDomainURL().toExternalForm();
    }
}