force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

mdapi/objects/Configurazioni__c/Configurazioni__c.object-meta.xml
<CustomObject>
    <label>Configurazione</label>
    <nameField>
        <displayFormat>CFG-{0000}</displayFormat>
        <label>Configurazione Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configurazioni__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configurazioni</relationshipLabel>
    <relationshipName>Configurazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configurazioni__c/fields/Attiva__c.field-meta.xml
<CustomField>
    <fullName>Attiva__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attiva</label>
    <type>Checkbox</type>
</CustomField>

mdapi/objects/Configurazioni__c/fields/Tipo_Configurazione__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Configurazione__c</fullName>
    <label>Tipo Configurazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Configurazioni__c/fields/Valore__c.field-meta.xml
<CustomField>
    <fullName>Valore__c</fullName>
    <label>Valore</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Fattura</label>
    <nameField>
        <displayFormat>Fattura-{00000000}</displayFormat>
        <label>Codice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fatture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Medical_Center__c.field-meta.xml
<CustomField>
    <fullName>Medical_Center__c</fullName>
    <label>Medical Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/classes/ConfigurazioniDefaultValueHelperTest.cls
@IsTest
private class ConfigurazioniDefaultValueHelperTest {
    @IsTest
    static void testRetrieveMedicalCenterDefaults() {
        Account partner = new Account(Name = 'Partner Default');
        insert partner;

        Account otherPartner = new Account(Name = 'Partner Secondario');
        insert otherPartner;

        Configurazioni__c initialConfiguration = new Configurazioni__c(
            Account__c = partner.Id,
            Attiva__c = true,
            Tipo_Configurazione__c = 'Valore di Default',
            Object_Name__c = 'Invoice__c',
            Field_Name__c = 'Medical_Center__c',
            Valore__c = ' Centro Originale '
        );
        insert initialConfiguration;

        Configurazioni__c latestConfiguration = new Configurazioni__c(
            Account__c = partner.Id,
            Attiva__c = true,
            Tipo_Configurazione__c = 'Valore di Default',
            Object_Name__c = 'Invoice__c',
            Field_Name__c = 'Medical_Center__c',
            Valore__c = ' Nuovo Centro '
        );
        insert latestConfiguration;

        Configurazioni__c inactiveConfiguration = new Configurazioni__c(
            Account__c = partner.Id,
            Attiva__c = false,
            Tipo_Configurazione__c = 'Valore di Default',
            Object_Name__c = 'Invoice__c',
            Field_Name__c = 'Medical_Center__c',
            Valore__c = 'Non utilizzato'
        );
        insert inactiveConfiguration;

        Configurazioni__c otherFieldConfiguration = new Configurazioni__c(
            Account__c = partner.Id,
            Attiva__c = true,
            Tipo_Configurazione__c = 'Valore di Default',
            Object_Name__c = 'Invoice__c',
            Field_Name__c = 'Another_Field__c',
            Valore__c = 'Non rilevante'
        );
        insert otherFieldConfiguration;

        Configurazioni__c otherPartnerConfiguration = new Configurazioni__c(
            Account__c = otherPartner.Id,
            Attiva__c = true,
            Tipo_Configurazione__c = 'Valore di Default',
            Object_Name__c = 'Invoice__c',
            Field_Name__c = 'Medical_Center__c',
            Valore__c = 'Altro Centro'
        );
        insert otherPartnerConfiguration;

        Test.startTest();
        List<String> defaults = ConfigurazioniDefaultValueHelper.retrieveMedicalCenterDefaults(
            new List<Id>{ partner.Id, otherPartner.Id, null }
        );
        Test.stopTest();

        System.assertEquals(3, defaults.size(), 'Deve essere restituito un valore per ogni input.');
        System.assertEquals('Nuovo Centro', defaults[0], 'Il valore più recente e attivo deve essere utilizzato.');
        System.assertEquals('Altro Centro', defaults[1], 'Il valore dell\'altro partner deve essere restituito.');
        System.assertEquals(null, defaults[2], 'Gli account null devono produrre un risultato nullo.');
    }
}