force-app/main/default/objects/Account/fields/Default_per_Budgets__c.field-meta.xml
<CustomField>
    <fullName>Default_per_Budgets__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default per Budgets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Grande Donatore</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Structure.recordType-meta.xml
<RecordType>
    <fullName>Structure</fullName>
    <active>true</active>
    <label>Fornitore</label>
</RecordType>

mdapi/objects/TicketAvailability__c/TicketAvailability__c.object-meta.xml
<CustomObject>
    <label>Offerta</label>
    <nameField>
        <displayFormat>Offerta-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offerte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/TicketAvailability__c/fields/NumberUses__c.field-meta.xml
<CustomField>
    <fullName>NumberUses__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Numero Utilizzi</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/OfferExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpirationDate__c</fullName>
    <label>Data Scadenza Offerta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>PartnerTicketAvailabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Stato</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponibile</fullName>
                <default>true</default>
                <label>Disponibile</label>
            </value>
            <value>
                <fullName>Prenotato</fullName>
            </value>
            <value>
                <fullName>Utilizzato</fullName>
            </value>
            <value>
                <fullName>Scaduto</fullName>
            </value>
            <value>
                <fullName>Fatturato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornitore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offerte (Struttura)</relationshipLabel>
    <relationshipName>TicketAvailabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <label>Nome Abbonamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/TicketType__c.field-meta.xml
<CustomField>
    <fullName>TicketType__c</fullName>
    <label>Tipologia Offerta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TicketType</valueSetName>
    </valueSet>
</CustomField>

mdapi/globalValueSets/TicketType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biglietto</fullName>
    </customValue>
    <customValue>
        <fullName>Abbonamento</fullName>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>Biglietti Multipli</fullName>
        <isActive>false</isActive>
        <label>Biglietti Multipli</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <masterLabel>Tipologia Biglietto</masterLabel>
</GlobalValueSet>

mdapi/classes/OffersControllerTest.cls
@isTest
private class OffersControllerTest {

    private class TestData {
        Account partnerAccount;
        Account secondaryPartner;
        Account defaultAccount;
        Account nonPartnerAccount;
        Account structureOne;
        Account structureTwo;
    }

    private static String ticketTypePrimaryValue;
    private static String ticketTypeSecondaryValue;
    private static String ticketTypeSearchValue;
    private static final String SEARCH_KEYWORD = 'SearchableOffer';

    @testSetup
    static void setupData() {
        Map<String, Schema.RecordTypeInfo> accountRecordTypes = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName();

        Id partnerRecordTypeId = accountRecordTypes.get('Partner').getRecordTypeId();
        Id structureRecordTypeId = accountRecordTypes.containsKey('Structure')
            ? accountRecordTypes.get('Structure').getRecordTypeId()
            : null;

        System.assertNotEquals(
            null,
            structureRecordTypeId,
            'Structure record type must exist for Account'
        );

        List<String> activeTicketTypes = new List<String>();
        for (Schema.PicklistEntry entry : TicketAvailability__c.TicketType__c.getDescribe().getPicklistValues()) {
            if (entry.isActive()) {
                activeTicketTypes.add(entry.getValue());
            }
        }
        System.assert(
            !activeTicketTypes.isEmpty(),
            'Test setup requires at least one active TicketType__c value.'
        );
        ticketTypePrimaryValue = activeTicketTypes[0];
        ticketTypeSecondaryValue = activeTicketTypes.size() > 1
            ? activeTicketTypes[1]
            : ticketTypePrimaryValue;
        ticketTypeSearchValue = activeTicketTypes.size() > 2
            ? activeTicketTypes[2]
            : ticketTypePrimaryValue;

        Account partnerAccount = new Account(
            Name = 'Test Partner Account',
            RecordTypeId = partnerRecordTypeId,
            Default_per_Budgets__c = false
        );
        Account secondaryPartner = new Account(
            Name = 'Other Partner Account',
            RecordTypeId = partnerRecordTypeId,
            Default_per_Budgets__c = false
        );
        Account defaultAccount = new Account(
            Name = 'Default Budget Account',
            Default_per_Budgets__c = true
        );
        Account nonPartnerAccount = new Account(
            Name = 'Standard Account',
            Default_per_Budgets__c = false
        );
        Account structureOne = new Account(
            Name = 'Teatro Alfa',
            RecordTypeId = structureRecordTypeId
        );
        Account structureTwo = new Account(
            Name = 'Cinema Beta',
            RecordTypeId = structureRecordTypeId
        );

        insert new List<Account>{
            partnerAccount,
            secondaryPartner,
            defaultAccount,
            nonPartnerAccount,
            structureOne,
            structureTwo
        };

        Date futureDate = Date.today().addDays(30);

        insert new List<TicketAvailability__c>{
            new TicketAvailability__c(
                Partner__c = partnerAccount.Id,
                Structure__c = structureOne.Id,
                TicketType__c = ticketTypePrimaryValue,
                State__c = 'Prenotato',
                NumberUses__c = 1,
                OfferExpirationDate__c = futureDate
            ),
            new TicketAvailability__c(
                Partner__c = partnerAccount.Id,
                Structure__c = structureTwo.Id,
                TicketType__c = ticketTypeSecondaryValue,
                State__c = 'Scaduto',
                NumberUses__c = 2,
                OfferExpirationDate__c = futureDate
            ),
            new TicketAvailability__c(
                Partner__c = partnerAccount.Id,
                Structure__c = structureOne.Id,
                TicketType__c = ticketTypePrimaryValue,
                State__c = 'Disponibile',
                NumberUses__c = 3,
                OfferExpirationDate__c = futureDate
            ),
            new TicketAvailability__c(
                Partner__c = secondaryPartner.Id,
                Structure__c = structureTwo.Id,
                TicketType__c = ticketTypeSecondaryValue,
                State__c = 'Utilizzato',
                NumberUses__c = 1,
                OfferExpirationDate__c = futureDate
            ),
            new TicketAvailability__c(
                Partner__c = defaultAccount.Id,
                Structure__c = structureOne.Id,
                SubscriptionName__c = SEARCH_KEYWORD + ' 1',
                TicketType__c = ticketTypeSearchValue,
                State__c = 'Fatturato',
                NumberUses__c = 5,
                OfferExpirationDate__c = futureDate
            ),
            new TicketAvailability__c(
                Partner__c = defaultAccount.Id,
                Structure__c = structureTwo.Id,
                SubscriptionName__c = SEARCH_KEYWORD + ' 2',
                TicketType__c = ticketTypeSearchValue,
                State__c = 'Disponibile',
                NumberUses__c = 1,
                OfferExpirationDate__c = futureDate
            )
        };
    }

    @isTest
    static void testPartnerUserReceivesFilteredStates() {
        TestData data = loadAccounts();
        setCurrentUserCompany(data.partnerAccount.Name);

        OffersController.TicketAvailabilityResponse response = callController(null, true);

        System.assertEquals(false, response.isDefaultPartner, 'Partner flag should be false');
        System.assertEquals(2, response.records.size(), 'Partner should see limited states');

        Set<String> states = new Set<String>();
        for (TicketAvailability__c record : response.records) {
            System.assertEquals(data.partnerAccount.Id, record.Partner__c, 'Only own partner records returned');
            states.add(record.State__c);
        }

        System.assert(states.contains('Prenotato'));
        System.assert(states.contains('Scaduto'));
        System.assert(!states.contains('Disponibile'));
        System.assertEquals(new Set<String>{'Prenotato', 'Scaduto'}, new Set<String>(response.availableStates));

        Set<Id> providerIds = new Set<Id>();
        for (OffersController.StructureOption option : response.availableStructures) {
            if (String.isNotBlank(option.value)) {
                providerIds.add(Id.valueOf(option.value));
            }
        }
        System.assertEquals(
            new Set<Id>{data.structureOne.Id, data.structureTwo.Id},
            providerIds,
            'Partner should only see own providers'
        );
    }

    @isTest
    static void testPartnerUserWithStateFilter() {
        TestData data = loadAccounts();
        setCurrentUserCompany(data.partnerAccount.Name);

        OffersController.TicketAvailabilityResponse response =
            OffersController.getTicketAvailabilities(
                new List<String>{'Scaduto'},
                50,
                0,
                null,
                false,
                null
            );

        System.assertEquals(1, response.records.size(), 'State filter applied');
        System.assertEquals('Scaduto', response.records[0].State__c);
    }

    @isTest
    static void testDefaultPartnerSeesAllStates() {
        TestData data = loadAccounts();
        setCurrentUserCompany(data.defaultAccount.Name);

        OffersController.TicketAvailabilityResponse response = callController(null, true);

        System.assertEquals(true, response.isDefaultPartner, 'Default partner flag');
        System.assertEquals(6, response.records.size(), 'Default user sees all records');

        Set<Id> partnerIds = new Set<Id>();
        Set<String> states = new Set<String>();
        for (TicketAvailability__c record : response.records) {
            partnerIds.add(record.Partner__c);
            states.add(record.State__c);
        }

        System.assertEquals(new Set<Id>{
            data.partnerAccount.Id,
            data.secondaryPartner.Id,
            data.defaultAccount.Id
        }, partnerIds);
        System.assert(states.contains('Disponibile'));
        System.assert(states.contains('Fatturato'));
        System.assertEquals(states, new Set<String>(response.availableStates));

        Set<Id> allProviderIds = new Set<Id>();
        for (OffersController.StructureOption option : response.availableStructures) {
            if (String.isNotBlank(option.value)) {
                allProviderIds.add(Id.valueOf(option.value));
            }
        }
        System.assertEquals(
            new Set<Id>{data.structureOne.Id, data.structureTwo.Id},
            allProviderIds,
            'Default partner should see all provider options'
        );
    }

    @isTest
    static void testDefaultPartnerFiltersByStructure() {
        TestData data = loadAccounts();
        setCurrentUserCompany(data.defaultAccount.Name);

        OffersController.TicketAvailabilityResponse response =
            OffersController.getTicketAvailabilities(
                null,
                50,
                0,
                null,
                false,
                data.structureOne.Id
            );

        System.assert(response.records.size() > 0, 'Expected records for selected provider');
        for (TicketAvailability__c record : response.records) {
            System.assertEquals(data.structureOne.Id, record.Structure__c);
        }
    }

    @isTest
    static void testSearchTermFiltersResults() {
        TestData data = loadAccounts();
        setCurrentUserCompany(data.defaultAccount.Name);

        OffersController.TicketAvailabilityResponse response =
            OffersController.getTicketAvailabilities(
                null,
                50,
                0,
                SEARCH_KEYWORD,
                false,
                null
            );

        System.assertEquals(2, response.records.size());
        for (TicketAvailability__c record : response.records) {
            System.assertEquals(data.defaultAccount.Id, record.Partner__c);
            System.assert(record.SubscriptionName__c != null && record.SubscriptionName__c.contains(SEARCH_KEYWORD));
        }
    }

    @isTest
    static void testUnmatchedUserGetsEmptySet() {
        setCurrentUserCompany('Unknown Company');

        OffersController.TicketAvailabilityResponse response = callController(null, true);

        System.assertEquals(0, response.records.size());
        System.assertEquals(false, response.isDefaultPartner);
    }

    @isTest
    static void testNonPartnerAccountBlocked() {
        TestData data = loadAccounts();
        setCurrentUserCompany(data.nonPartnerAccount.Name);

        OffersController.TicketAvailabilityResponse response = callController(null, true);

        System.assertEquals(0, response.records.size());
    }

    private static OffersController.TicketAvailabilityResponse callController(List<String> states, Boolean includeStates) {
        return OffersController.getTicketAvailabilities(
            states,
            50,
            0,
            null,
            includeStates,
            null
        );
    }

    private static void setCurrentUserCompany(String companyName) {
        User runningUser = [
            SELECT Id, CompanyName
            FROM User
            WHERE Id = :UserInfo.getUserId()
        ];
        runningUser.CompanyName = companyName;
        update runningUser;
    }

    private static TestData loadAccounts() {
        TestData data = new TestData();
        Map<String, Account> accountsByName = new Map<String, Account>();
        for (Account acc : [
            SELECT Id, Name, Default_per_Budgets__c, RecordType.DeveloperName
            FROM Account
            WHERE Name IN (
                'Test Partner Account',
                'Other Partner Account',
                'Default Budget Account',
                'Standard Account',
                'Teatro Alfa',
                'Cinema Beta'
            )
        ]) {
            accountsByName.put(acc.Name, acc);
        }
        data.partnerAccount = accountsByName.get('Test Partner Account');
        data.secondaryPartner = accountsByName.get('Other Partner Account');
        data.defaultAccount = accountsByName.get('Default Budget Account');
        data.nonPartnerAccount = accountsByName.get('Standard Account');
        data.structureOne = accountsByName.get('Teatro Alfa');
        data.structureTwo = accountsByName.get('Cinema Beta');
        return data;
    }
}