force-app/main/default/objects/Account/fields/DEFAULT__c.field-meta.xml
<CustomField>
    <fullName>DEFAULT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default per Fatture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRATUITO__c.field-meta.xml
<CustomField>
    <fullName>GRATUITO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestazioni Gratuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Donatori</relationshipLabel>
    <relationshipName>Donatori</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

mdapi/objects/Anno_Reportistica__c/Anno_Reportistica__c.object-meta.xml
<CustomObject>
    <label>Anno Reportistica</label>
    <nameField>
        <label>Anno di Reportistica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anni Reportistica</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Anno_Reportistica__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Anni Reportistica</relationshipLabel>
    <relationshipName>Anni_Reportistica</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Donor_Overview__c/Donor_Overview__c.object-meta.xml
<CustomObject>
    <label>Donatore per Programma</label>
    <nameField>
        <label>Donor Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Programma</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Donor_Overview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Donors Overview</relationshipLabel>
    <relationshipName>Donors_Overview</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donor_Overview__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori</relationshipLabel>
    <relationshipName>Overview_Donatori</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GiftDesignation/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GiftDesignation/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/Overview_Budget_per_Anno__c.object-meta.xml
<CustomObject>
    <label>Budget per Anno</label>
    <nameField>
        <label>Codice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Anno_Reportistica__c.field-meta.xml
<CustomField>
    <fullName>Anno_Reportistica__c</fullName>
    <label>Anno Reportistica</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Budget per Anno</relationshipLabel>
    <relationshipName>Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Anni di Reportistica</relationshipLabel>
    <relationshipName>Anni_di_Reportistica</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Donor_Overview__c.field-meta.xml
<CustomField>
    <fullName>Donor_Overview__c</fullName>
    <label>Donor Overview</label>
    <referenceTo>Donor_Overview__c</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori per Anno</relationshipLabel>
    <relationshipName>Overview_Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Donatori per Anno</relationshipLabel>
    <relationshipName>Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Totali_Budget_Anno__c/Totali_Budget_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Budget Anno</label>
    <nameField>
        <label>Totali Budget Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Budget Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Totali_Budget_Anno__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipLabel>Totali Budget Anno</relationshipLabel>
    <relationshipName>Totali_Budget_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Totali_Budget_Anno__c/fields/Donatore__c.field-meta.xml
<CustomField>
    <fullName>Donatore__c</fullName>
    <label>Donatore</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Totali Budget Anno</relationshipLabel>
    <relationshipName>Totali_Budget_Anno</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Totali_Donatore_Anno__c/Totali_Donatore_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Donatore Anno</label>
    <nameField>
        <label>Totali Donatore Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Donatore Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Totali_Donatore_Anno__c/fields/Donatore__c.field-meta.xml
<CustomField>
    <fullName>Donatore__c</fullName>
    <label>Donatore</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Totali Donatore Anno</relationshipLabel>
    <relationshipName>Totali_Donatore_Anno</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Totali_Donatore_Anno__c/fields/Donatore_Programma__c.field-meta.xml
<CustomField>
    <fullName>Donatore_Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donatore Programma</label>
    <referenceTo>Donor_Overview__c</referenceTo>
    <relationshipLabel>Totali Donatore Anno</relationshipLabel>
    <relationshipName>Totali_Donatore_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/classes/InvoiceTestDataFactory.cls
public with sharing class InvoiceTestDataFactory {
  public class Setup {
    public Id programId;
    public Id budgetId;
    public Id obId;
    public Id accDefaultId;
    public Id accFreeId;
    public Id accNormalId;
    public Id ryNormalId;
    public Id ryFreeId;
    public Id ryDefaultId;
    public Id totBudId;
    public Id totDonId;
  }

  public static Setup createBase(String year) {
    Setup s = new Setup();

    Program prog = new Program(Name = 'Test Program');
    insert prog; s.programId = prog.Id;

    // Partner Account richiesto da GiftDesignation.Partner__c
    Account partnerAcc = new Account(Name = 'Partner Test');
    insert partnerAcc;

    GiftDesignation gd = new GiftDesignation(Name = 'Test Budget', Partner__c = partnerAcc.Id);
    try { gd.put('Program__c', s.programId); } catch (Exception ignore) {}
    insert gd; s.budgetId = gd.Id;

    // Donor Accounts (create Normal first to use it in Totali)
    Account accN = new Account(Name = 'Donor A');
    insert accN; s.accNormalId = accN.Id;
    Account accDef = new Account(Name = 'DEFAULT', DEFAULT__c = true);
    insert accDef; s.accDefaultId = accDef.Id;
    Account accFree = new Account(Name = 'GRATUITO', GRATUITO__c = true);
    insert accFree; s.accFreeId = accFree.Id;

    // Donor Overviews per Programma (richiesti da Reporting_Year__c)
    Donor_Overview__c ovNormal = new Donor_Overview__c(
      Account__c = s.accNormalId,
      Programma__c = s.programId,
      Name = 'Overview - Donor A - ' + [SELECT Name FROM Program WHERE Id = :s.programId].Name
    );
    insert ovNormal;
    Donor_Overview__c ovFree = new Donor_Overview__c(
      Account__c = s.accFreeId,
      Programma__c = s.programId,
      Name = 'Overview - GRATUITO - ' + [SELECT Name FROM Program WHERE Id = :s.programId].Name
    );
    insert ovFree;
    Donor_Overview__c ovDefault = new Donor_Overview__c(
      Account__c = s.accDefaultId,
      Programma__c = s.programId,
      Name = 'Overview - DEFAULT - ' + [SELECT Name FROM Program WHERE Id = :s.programId].Name
    );
    insert ovDefault;

    // Totali SObjects (populate required fields)
    SObject tb = (SObject) Schema.getGlobalDescribe().get('Totali_Budget_Anno__c').newSObject();
    tb.put('Name', 'TB');
    // Best guess: required link to Budget and Donor
    try { tb.put('Budget__c', s.budgetId); } catch (Exception ignore) {}
    try { tb.put('Donatore__c', s.accNormalId); } catch (Exception ignore) {}
    try { tb.put('Programma__c', s.programId); } catch (Exception ignore) {}
    try { tb.put('Anno__c', year); } catch (Exception ignore) {}
    insert tb; s.totBudId = (Id) tb.get('Id');

    SObject td = (SObject) Schema.getGlobalDescribe().get('Totali_Donatore_Anno__c').newSObject();
    td.put('Name', 'TD-Normal');
    try { td.put('Donatore__c', s.accNormalId); } catch (Exception ignore) {}
    try { td.put('Donatore_Programma__c', ovNormal.Id); } catch (Exception ignore) {}
    try { td.put('Year__c', year); } catch (Exception ignore) {}
    insert td; s.totDonId = (Id) td.get('Id');

    SObject tdDef = (SObject) Schema.getGlobalDescribe().get('Totali_Donatore_Anno__c').newSObject();
    tdDef.put('Name', 'TD-Default');
    try { tdDef.put('Donatore__c', s.accDefaultId); } catch (Exception ignore) {}
    try { tdDef.put('Donatore_Programma__c', ovDefault.Id); } catch (Exception ignore) {}
    try { tdDef.put('Year__c', year); } catch (Exception ignore) {}
    insert tdDef;

    SObject tdFree = (SObject) Schema.getGlobalDescribe().get('Totali_Donatore_Anno__c').newSObject();
    tdFree.put('Name', 'TD-Free');
    try { tdFree.put('Donatore__c', s.accFreeId); } catch (Exception ignore) {}
    try { tdFree.put('Donatore_Programma__c', ovFree.Id); } catch (Exception ignore) {}
    try { tdFree.put('Year__c', year); } catch (Exception ignore) {}
    insert tdFree;

    // Ensure Anno_Reportistica__c exists and link it
    Anno_Reportistica__c ar = new Anno_Reportistica__c(
      Name = year,
      Programma__c = s.programId
    );
    insert ar;

    Overview_Budget_per_Anno__c ob = new Overview_Budget_per_Anno__c(
      Name = 'OB '+year,
      Budget__c = s.budgetId,
      Anno__c = year,
      Programma__c = s.programId,
      Anno_Reportistica__c = ar.Id,
      Totali_Budget_Anno__c = s.totBudId
    );
    insert ob; s.obId = ob.Id;

    Reporting_Year__c ryN = new Reporting_Year__c(
      Name = 'RY '+year,
      Donor_Overview__c = ovNormal.Id,
      Anno__c = ar.Id,
      Account__c = s.accNormalId,
      Year__c = year,
      Programma__c = s.programId,
      Totali_Donatore_Anno__c = s.totDonId
    );
    insert ryN; s.ryNormalId = ryN.Id;

    Reporting_Year__c ryF = new Reporting_Year__c(
      Name = 'RY FREE '+year,
      Donor_Overview__c = ovFree.Id,
      Anno__c = ar.Id,
      Account__c = s.accFreeId,
      Year__c = year,
      Programma__c = s.programId,
      Totali_Donatore_Anno__c = (Id) tdFree.get('Id')
    );
    insert ryF; s.ryFreeId = ryF.Id;

    Reporting_Year__c ryD = new Reporting_Year__c(
      Name = 'RY DEFAULT '+year,
      Donor_Overview__c = ovDefault.Id,
      Anno__c = ar.Id,
      Account__c = s.accDefaultId,
      Year__c = year,
      Programma__c = s.programId,
      Totali_Donatore_Anno__c = (Id) tdDef.get('Id')
    );
    insert ryD; s.ryDefaultId = ryD.Id;

    return s;
  }
}