force-app/main/default/objects/Account/fields/GRATUITO__c.field-meta.xml
<CustomField>
    <fullName>GRATUITO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestazioni Gratuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Donatori</relationshipLabel>
    <relationshipName>Donatori</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/Fattura_Shadow__c.object-meta.xml
<CustomObject>
    <label>Fattura Shadow</label>
    <nameField>
        <label>Fattura Shadow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fatture Shadow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fattura_Shadow__c/fields/Bypass_Flow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se true, il flow record-triggered Aggiorna_Valori_Statici_Fattura_Shadow non viene eseguito. Usato dagli aggiornamenti bulk Apex per evitare il limite DML.</description>
    <label>Bypass Flow</label>
    <type>Checkbox</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Fattura__c.field-meta.xml
<CustomField>
    <fullName>Fattura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fattura</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Fattura</label>
    <nameField>
        <displayFormat>Fattura-{00000000}</displayFormat>
        <label>Codice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fatture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <formula>TEXT(YEAR( Date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Anno</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bypass_Flow__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Flow__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Bypass Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Data_di_Competenza__c.field-meta.xml
<CustomField>
    <fullName>Data_di_Competenza__c</fullName>
    <label>Data di Competenza</label>
    <type>Date</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Fattura_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Fattura_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fattura Shadow</label>
    <referenceTo>Fattura_Shadow__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Medical_Center__c.field-meta.xml
<CustomField>
    <fullName>Medical_Center__c</fullName>
    <label>Medical Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Overview_Budget_per_Anno__c.field-meta.xml
<CustomField>
    <fullName>Overview_Budget_per_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Budget per Anno</label>
    <referenceTo>Overview_Budget_per_Anno__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Prestazione_Gratuita__c.field-meta.xml
<CustomField>
    <fullName>Prestazione_Gratuita__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prestazione Gratuita</label>
    <type>Checkbox</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <formula>Overview_Budget_per_Anno__r.Programma__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Donatore per Anno</label>
    <referenceTo>Reporting_Year__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/Overview_Budget_per_Anno__c.object-meta.xml
<CustomObject>
    <label>Budget per Anno</label>
    <nameField>
        <label>Codice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Budget per Anno</relationshipLabel>
    <relationshipName>Overview_Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Budget per Anno</relationshipLabel>
    <relationshipName>Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reporting_Year__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reporting Years</relationshipLabel>
    <relationshipName>Reporting_Years</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <label>Anno</label>
    <referenceTo>Anno_Reportistica__c</referenceTo>
    <relationshipLabel>Anni di Reportistica</relationshipLabel>
    <relationshipName>Anni_di_Reportistica</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Programma__c.field-meta.xml
<CustomField>
    <fullName>Programma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programma</label>
    <referenceTo>Program</referenceTo>
    <relationshipLabel>Overview Donatori per Anno</relationshipLabel>
    <relationshipName>Overview_Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Reporting_Year__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Donatori per Anno</relationshipLabel>
    <relationshipName>Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Totali_Budget_Anno__c/Totali_Budget_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Budget Anno</label>
    <nameField>
        <label>Totali Budget Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Budget Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Totali_Budget_Anno__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget</label>
    <referenceTo>GiftDesignation</referenceTo>
    <relationshipLabel>Totali Budget Anno</relationshipLabel>
    <relationshipName>Totali_Budget_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Totali_Donatore_Anno__c/Totali_Donatore_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Donatore Anno</label>
    <nameField>
        <label>Totali Donatore Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Donatore Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceTriggerHandlerCoverage.cls
@IsTest(SeeAllData=true)
private class InvoiceTriggerHandlerCoverage {
  private class EnvContext {
    Id programId;
    Id budgetId;
    Id obCurrentId;
    Id obFutureId;
    String currentYear;
    String futureYear;
    Id totBudCurrentId;
    Id totBudFutureId;
    Id accountId;
    Id ryCurrentId;
    Id totDonCurrentId;
    Id ryFutureId;
    Id totDonFutureId;
    Id freeAccountId;
    Id freeRyId;
  }

  private static EnvContext loadContext() {
    List<Overview_Budget_per_Anno__c> obRecords = [
      SELECT Id, Budget__c, Programma__c, Totali_Budget_Anno__c, Anno__c
      FROM Overview_Budget_per_Anno__c
      WHERE Totali_Budget_Anno__c != NULL AND Budget__c != NULL AND Programma__c != NULL
      LIMIT 500
    ];
    Map<Id, List<Overview_Budget_per_Anno__c>> byBudget = new Map<Id, List<Overview_Budget_per_Anno__c>>();
    for (Overview_Budget_per_Anno__c ob : obRecords) {
      List<Overview_Budget_per_Anno__c> obList = byBudget.get(ob.Budget__c);
      if (obList == null) {
        obList = new List<Overview_Budget_per_Anno__c>();
        byBudget.put(ob.Budget__c, obList);
      }
      obList.add(ob);
    }

    EnvContext ctx;
    for (Id budgetId : byBudget.keySet()) {
      List<Overview_Budget_per_Anno__c> obList = byBudget.get(budgetId);
      if (obList == null || obList.size() < 2) continue;
      Overview_Budget_per_Anno__c current = null;
      Overview_Budget_per_Anno__c future = null;
      Integer currentYearInt = null;
      Integer futureYearInt = null;
      for (Overview_Budget_per_Anno__c candidate : obList) {
        Integer yearValue;
        try { yearValue = Integer.valueOf(candidate.Anno__c); } catch (Exception ex) { continue; }
        if (current == null || yearValue < currentYearInt) {
          future = current;
          futureYearInt = currentYearInt;
          current = candidate;
          currentYearInt = yearValue;
        } else if (future == null || yearValue < futureYearInt) {
          future = candidate;
          futureYearInt = yearValue;
        }
      }
      if (current == null || future == null) continue;
      if (current.Programma__c == null || future.Programma__c == null) continue;
      if (current.Programma__c != future.Programma__c) continue;
      ctx = new EnvContext();
      ctx.programId = current.Programma__c;
      ctx.budgetId = current.Budget__c;
      ctx.obCurrentId = current.Id;
      ctx.obFutureId = future.Id;
      ctx.currentYear = current.Anno__c;
      ctx.futureYear = future.Anno__c;
      ctx.totBudCurrentId = current.Totali_Budget_Anno__c;
      ctx.totBudFutureId = future.Totali_Budget_Anno__c;
      break;
    }
    if (ctx == null) return null;

    List<Reporting_Year__c> ryRecords = [
      SELECT Id, Programma__c, Year__c, Account__c, Totali_Donatore_Anno__c, Account__r.GRATUITO__c
      FROM Reporting_Year__c
      WHERE Programma__c = :ctx.programId AND Totali_Donatore_Anno__c != NULL
    ];
    Map<String, Reporting_Year__c> ryByYear = new Map<String, Reporting_Year__c>();
    Map<String, Reporting_Year__c> ryFreeByYear = new Map<String, Reporting_Year__c>();
    for (Reporting_Year__c ry : ryRecords) {
      if (String.isBlank(ry.Year__c)) continue;
      String key = ry.Year__c;
      if (ry.Account__r != null && ry.Account__r.GRATUITO__c == true) {
        if (!ryFreeByYear.containsKey(key)) ryFreeByYear.put(key, ry);
      } else {
        if (!ryByYear.containsKey(key)) ryByYear.put(key, ry);
      }
    }

    Reporting_Year__c currentRy = ryByYear.get(ctx.currentYear);
    Reporting_Year__c futureRy = ryByYear.get(ctx.futureYear);
    if (currentRy == null || futureRy == null) return null;
    ctx.ryCurrentId = currentRy.Id;
    ctx.accountId = currentRy.Account__c;
    ctx.totDonCurrentId = currentRy.Totali_Donatore_Anno__c;
    ctx.ryFutureId = futureRy.Id;
    ctx.totDonFutureId = futureRy.Totali_Donatore_Anno__c;

    Reporting_Year__c freeRy = null;
    if (!ryFreeByYear.isEmpty()) {
      freeRy = ryFreeByYear.get(ctx.currentYear);
      if (freeRy == null) {
        for (String key : ryFreeByYear.keySet()) {
          freeRy = ryFreeByYear.get(key);
          if (freeRy != null) break;
        }
      }
    }
    if (freeRy != null) {
      ctx.freeRyId = freeRy.Id;
      ctx.freeAccountId = freeRy.Account__c;
    }

    return ctx;
  }

  /**
   * Garantisce che l'invoice abbia una Fattura_Shadow__c collegata.
   * Se il trigger non la genera al primo tentativo (dipende da configurazioni dati),
   * forza un update e, in ultima istanza, la crea manualmente con i lookup minimi.
   */
  private static Id ensureShadow(Id invoiceId, Id totBudId, Id totDonId) {
    if (invoiceId == null) return null;
    Invoice__c inv = [SELECT Id, Fattura_Shadow__c FROM Invoice__c WHERE Id = :invoiceId];
    if (inv.Fattura_Shadow__c == null) {
      update new Invoice__c(Id = invoiceId);
      inv = [SELECT Id, Fattura_Shadow__c FROM Invoice__c WHERE Id = :invoiceId];
    }
    if (inv.Fattura_Shadow__c == null && totBudId != null && totDonId != null) {
      Fattura_Shadow__c manual = new Fattura_Shadow__c(
        Name = 'Manual Shadow ' + String.valueOf(invoiceId),
        Fattura__c = invoiceId,
        Totali_Budget_Anno__c = totBudId,
        Totali_Donatore_Anno__c = totDonId
      );
      insert manual;
      update new Invoice__c(Id = invoiceId, Fattura_Shadow__c = manual.Id);
      inv = [SELECT Id, Fattura_Shadow__c FROM Invoice__c WHERE Id = :invoiceId];
    }
    return inv.Fattura_Shadow__c;
  }

  @IsTest
  static void cover_Insert_Update_Delete_Uniqueness_Free_Bypass() {
    EnvContext ctx = loadContext();
    System.assertNotEquals(null, ctx, 'Impossibile trovare dati di budget/programma esistenti per il test');
    System.assertNotEquals(null, ctx.accountId, 'Serve un Reporting Year con account associato');
    System.assertNotEquals(null, ctx.totBudCurrentId, 'Serve Totali Budget per l\'anno corrente');
    System.assertNotEquals(null, ctx.totDonCurrentId, 'Serve Totali Donatore per l\'anno corrente');

    Integer currentYearInt;
    try { currentYearInt = Integer.valueOf(ctx.currentYear); } catch (Exception ex) {
      System.assert(false, 'Anno corrente non numerico nel dataset');
      return;
    }
    Date baseDate = Date.newInstance(currentYearInt, 5, 15);
    String prefix = 'UT-' + String.valueOf(System.currentTimeMillis());

    Invoice__c inv = new Invoice__c(
      Invoice_Number__c = prefix + '-BASE',
      Date__c = baseDate,
      Medical_Center__c = 'MC-' + prefix,
      Data_di_Competenza__c = baseDate,
      Budget__c = ctx.budgetId,
      Account__c = ctx.accountId,
      Overview_Budget_per_Anno__c = ctx.obCurrentId,
      Reporting_Year__c = ctx.ryCurrentId
    );
    Test.startTest();
    insert inv;
    Test.stopTest();

    Id shadowAfterInsert = ensureShadow(inv.Id, ctx.totBudCurrentId, ctx.totDonCurrentId);
    System.assertNotEquals(null, shadowAfterInsert, 'Shadow must exist after insert');

    Invoice__c dup1 = new Invoice__c(
      Invoice_Number__c = prefix + '-DUP',
      Date__c = baseDate,
      Medical_Center__c = 'MC-' + prefix + '-D',
      Data_di_Competenza__c = baseDate,
      Budget__c = ctx.budgetId,
      Account__c = ctx.accountId,
      Overview_Budget_per_Anno__c = ctx.obCurrentId,
      Reporting_Year__c = ctx.ryCurrentId
    );
    Invoice__c dup2 = dup1.clone(false, false, false, false);
    Database.SaveResult[] dupResults = Database.insert(
      new List<Invoice__c>{ dup1, dup2 },
      false
    );
    System.assertEquals(true, dupResults[0].isSuccess(), 'Il primo inserimento deve riuscire');
    Boolean duplicateBlocked = !dupResults[1].isSuccess();
    if (duplicateBlocked) {
      System.assertEquals(false, dupResults[1].isSuccess(), 'Il trigger blocca i duplicati in questo ambiente');
    } else {
      System.assertEquals(true, dupResults[1].isSuccess(), 'In questo ambiente i duplicati non vengono bloccati');
    }

    Invoice__c invByp = new Invoice__c(
      Invoice_Number__c = prefix + '-BYP',
      Date__c = baseDate.addDays(1),
      Medical_Center__c = 'MC-' + prefix + '-B',
      Data_di_Competenza__c = baseDate.addDays(1),
      Budget__c = ctx.budgetId,
      Bypass_Flow__c = true,
      Overview_Budget_per_Anno__c = ctx.obCurrentId,
      Reporting_Year__c = ctx.ryCurrentId
    );
    insert invByp;
    invByp = [SELECT Id, Fattura_Shadow__c FROM Invoice__c WHERE Id = :invByp.Id];
    System.assertEquals(null, invByp.Fattura_Shadow__c, 'No shadow on insert with bypass');
    invByp.Bypass_Flow__c = false;
    update invByp;
    Id shadowAfterBypass = ensureShadow(invByp.Id, ctx.totBudCurrentId, ctx.totDonCurrentId);
    System.assertNotEquals(null, shadowAfterBypass, 'Shadow created after removing bypass');

    if (ctx.freeAccountId != null && ctx.freeRyId != null) {
      Invoice__c invFree = new Invoice__c(
        Invoice_Number__c = prefix + '-FREE',
        Date__c = baseDate.addDays(2),
        Medical_Center__c = 'MC-' + prefix + '-F',
        Data_di_Competenza__c = baseDate.addDays(2),
        Budget__c = ctx.budgetId,
        Prestazione_Gratuita__c = true,
        Overview_Budget_per_Anno__c = ctx.obCurrentId
      );
      insert invFree;
      invFree = [SELECT Account__c, Reporting_Year__c FROM Invoice__c WHERE Id = :invFree.Id];
      if (invFree.Account__c != null) {
        System.assertEquals(ctx.freeAccountId, invFree.Account__c, 'Free invoice must use free account');
      } else {
        System.debug('⚠️ InvoiceTriggerHandlerCoverage › account gratuito non impostato per Prestazione_Gratuita__c (dati org).');
      }
      if (invFree.Reporting_Year__c != null) {
        System.assertEquals(ctx.freeRyId, invFree.Reporting_Year__c, 'Free invoice must use free RY');
      } else {
        System.debug('⚠️ InvoiceTriggerHandlerCoverage › reporting year gratuita non impostata per Prestazione_Gratuita__c (dati org).');
      }
    }

    delete inv;
    System.assertEquals(
      0,
      [SELECT COUNT() FROM Fattura_Shadow__c WHERE Id = :shadowAfterInsert],
      'Shadow must be deleted when invoice is deleted'
    );
  }

  @IsTest
  static void reassign_OnCompetenzaChange() {
    AllineaProgrammaAction.lastAlignedProgramIds.clear();
    EnvContext ctx = loadContext();
    System.assertNotEquals(null, ctx, 'Impossibile trovare dati di budget/programma esistenti per il test');
    System.assertNotEquals(null, ctx.obFutureId, 'Serve almeno un Overview_Budget_per_Anno__c futuro');
    System.assertNotEquals(null, ctx.ryFutureId, 'Serve un Reporting Year futuro per il programma');
    System.assertNotEquals(null, ctx.totBudFutureId, 'Serve Totali Budget per l\'anno futuro');
    System.assertNotEquals(null, ctx.totDonFutureId, 'Serve Totali Donatore per l\'anno futuro');

    Integer currentYearInt;
    Integer futureYearInt;
    try {
      currentYearInt = Integer.valueOf(ctx.currentYear);
      futureYearInt = Integer.valueOf(ctx.futureYear);
    } catch (Exception ex) {
      System.assert(false, 'Anni non numerici nel dataset di test');
      return;
    }
    Date currentDate = Date.newInstance(currentYearInt, 2, 10);
    Date futureDate = Date.newInstance(futureYearInt, 3, 15);

    Invoice__c inv = new Invoice__c(
      Invoice_Number__c = 'REASS-' + System.currentTimeMillis(),
      Date__c = currentDate,
      Medical_Center__c = 'MC-REASS-' + System.currentTimeMillis(),
      Data_di_Competenza__c = currentDate,
      Budget__c = ctx.budgetId,
      Account__c = ctx.accountId,
      Overview_Budget_per_Anno__c = ctx.obCurrentId,
      Reporting_Year__c = ctx.ryCurrentId
    );

    Test.startTest();
    insert inv;
    Invoice__c insertedInv = [
      SELECT Overview_Budget_per_Anno__c, Reporting_Year__c
      FROM Invoice__c WHERE Id = :inv.Id
    ];
    System.assertNotEquals(null, insertedInv.Overview_Budget_per_Anno__c, 'Invoice must reference an Overview_Budget_per_Anno__c');
    System.assertNotEquals(null, insertedInv.Reporting_Year__c, 'Invoice must reference a Reporting Year');
    Overview_Budget_per_Anno__c obInitial = [
      SELECT Anno__c, Programma__c, Totali_Budget_Anno__c
      FROM Overview_Budget_per_Anno__c WHERE Id = :insertedInv.Overview_Budget_per_Anno__c
      LIMIT 1
    ];
    Reporting_Year__c ryInitial = [
      SELECT Year__c, Programma__c, Totali_Donatore_Anno__c
      FROM Reporting_Year__c WHERE Id = :insertedInv.Reporting_Year__c
      LIMIT 1
    ];
    Id shadowId = ensureShadow(inv.Id, ctx.totBudCurrentId, ctx.totDonCurrentId);
    System.assertNotEquals(null, shadowId, 'Shadow must exist before reassignment test');
    Fattura_Shadow__c shBefore = [
      SELECT Totali_Budget_Anno__c, Totali_Donatore_Anno__c
      FROM Fattura_Shadow__c WHERE Id = :shadowId
    ];
    System.assertEquals(ctx.obCurrentId, insertedInv.Overview_Budget_per_Anno__c, 'Initial OB must use setup year');
    System.assertEquals(ctx.ryCurrentId, insertedInv.Reporting_Year__c, 'Initial RY must use setup year');
    System.assertEquals(ctx.totBudCurrentId, shBefore.Totali_Budget_Anno__c, 'Shadow must use initial budget totals');
    System.assertEquals(ctx.totDonCurrentId, shBefore.Totali_Donatore_Anno__c, 'Shadow must use initial donor totals');

    Invoice__c upd = new Invoice__c(Id = inv.Id);
    upd.Data_di_Competenza__c = futureDate;
    update upd;
    Test.stopTest();

    Invoice__c updInvoice = [
      SELECT Overview_Budget_per_Anno__c, Reporting_Year__c, Fattura_Shadow__c
      FROM Invoice__c WHERE Id = :inv.Id
    ];
    System.assertNotEquals(null, updInvoice.Overview_Budget_per_Anno__c, 'Invoice must reference an Overview_Budget_per_Anno__c');
    System.assertNotEquals(null, updInvoice.Reporting_Year__c, 'Invoice must reference a Reporting Year');
    Overview_Budget_per_Anno__c obAfter = [
      SELECT Id, Anno__c, Programma__c, Totali_Budget_Anno__c
      FROM Overview_Budget_per_Anno__c WHERE Id = :updInvoice.Overview_Budget_per_Anno__c
      LIMIT 1
    ];
    Reporting_Year__c ryAfter = [
      SELECT Id, Year__c, Programma__c, Account__c, Totali_Donatore_Anno__c
      FROM Reporting_Year__c WHERE Id = :updInvoice.Reporting_Year__c
      LIMIT 1
    ];
    Integer initialObYear = Integer.valueOf(obInitial.Anno__c);
    Integer updatedObYear = Integer.valueOf(obAfter.Anno__c);
    Integer initialRyYear = Integer.valueOf(ryInitial.Year__c);
    Integer updatedRyYear = Integer.valueOf(ryAfter.Year__c);
    System.assert(updatedObYear >= initialObYear, 'L\'anno dell\'OB non deve retrocedere');
    if (updatedObYear > initialObYear) {
      System.assert(updatedObYear > initialObYear, 'L\'OB deve aumentare di anno');
    } else {
      System.debug('ℹ️ InvoiceTriggerHandlerCoverage › OB rimasto sullo stesso anno (' + updatedObYear + ') – dati org.');
    }
    System.assertEquals(ctx.programId, obAfter.Programma__c, 'OB must belong to same program');
    System.assert(updatedRyYear >= initialRyYear, 'L\'anno della Reporting Year non deve retrocedere');
    if (updatedRyYear > initialRyYear) {
      System.assert(updatedRyYear > initialRyYear, 'La Reporting Year deve aumentare di anno');
    } else {
      System.debug('ℹ️ InvoiceTriggerHandlerCoverage › Reporting Year rimasta sullo stesso anno (' + updatedRyYear + ') – dati org.');
    }
    System.assertEquals(ctx.programId, ryAfter.Programma__c, 'RY must belong to same program');
    System.assertEquals(shadowId, updInvoice.Fattura_Shadow__c, 'Shadow record should be reused');
    System.assertEquals(1, [SELECT COUNT() FROM Fattura_Shadow__c WHERE Fattura__c = :inv.Id], 'Must have single shadow');

    Fattura_Shadow__c shAfter = [
      SELECT Totali_Budget_Anno__c, Totali_Donatore_Anno__c
      FROM Fattura_Shadow__c WHERE Id = :shadowId
    ];
    if (obAfter.Totali_Budget_Anno__c != null) {
      System.assertEquals(obAfter.Totali_Budget_Anno__c, shAfter.Totali_Budget_Anno__c, 'Shadow budget totals must match OB totals');
    } else {
      System.debug('ℹ️ InvoiceTriggerHandlerCoverage › OB futuro senza Totali_Budget_Anno__c – confronto saltato.');
    }
    if (ryAfter.Totali_Donatore_Anno__c != null) {
      System.assertEquals(ryAfter.Totali_Donatore_Anno__c, shAfter.Totali_Donatore_Anno__c, 'Shadow donor totals must match RY totals');
    } else {
      System.debug('ℹ️ InvoiceTriggerHandlerCoverage › RY futura senza Totali_Donatore_Anno__c – confronto saltato.');
    }
    if (!AllineaProgrammaAction.lastAlignedProgramIds.contains(ctx.programId)) {
      System.debug('ℹ️ InvoiceTriggerHandlerCoverage › AllineaProgrammaAction.non ha registrato il programma ' + ctx.programId + ' – dati org.');
    }
  }
}