force-app/main/default/objects/Account/fields/StructureCode__c.field-meta.xml
<CustomField>
    <fullName>StructureCode__c</fullName>
    <label>Codice Fornitore</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Structure.recordType-meta.xml
<RecordType>
    <fullName>Structure</fullName>
    <active>true</active>
    <label>Fornitore</label>
</RecordType>

force-app/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <label>Spettacolo</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Show__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <label>Data e Ora</label>
    <type>DateTime</type>
</CustomField>

mdapi/objects/Show__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Struttura</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows</relationshipLabel>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Show__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TypeShow</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/TicketAvailability__c.object-meta.xml
<CustomObject>
    <label>Offerta</label>
    <nameField>
        <displayFormat>Offerta-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offerte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/TicketAvailability__c/fields/EndValidity__c.field-meta.xml
<CustomField>
    <fullName>EndValidity__c</fullName>
    <label>Fine Validità</label>
    <type>DateTime</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/IssuanceType__c.field-meta.xml
<CustomField>
    <fullName>IssuanceType__c</fullName>
    <label>Tipologia Emissione</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TicketType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>IssuanceType</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/NumberUses__c.field-meta.xml
<CustomField>
    <fullName>NumberUses__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Numero Utilizzi</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/OfferExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpirationDate__c</fullName>
    <label>Data Scadenza Offerta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Tipologia Pagamento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IssuanceType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PaymentType</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/PriceDiscounted__c.field-meta.xml
<CustomField>
    <fullName>PriceDiscounted__c</fullName>
    <label>Prezzo Scontato</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/PriceFull__c.field-meta.xml
<CustomField>
    <fullName>PriceFull__c</fullName>
    <label>Prezzo Intero</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Show__c.field-meta.xml
<CustomField>
    <fullName>Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spettacolo</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipName>Biglietti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/StartValidity__c.field-meta.xml
<CustomField>
    <fullName>StartValidity__c</fullName>
    <label>Inizio Validità</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Stato</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponibile</fullName>
                <default>true</default>
                <label>Disponibile</label>
            </value>
            <value>
                <fullName>Prenotato</fullName>
            </value>
            <value>
                <fullName>Utilizzato</fullName>
            </value>
            <value>
                <fullName>Scaduto</fullName>
            </value>
            <value>
                <fullName>Fatturato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornitore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offerte (Struttura)</relationshipLabel>
    <relationshipName>TicketAvailabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <label>Nome Abbonamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionType__c</fullName>
    <label>Tipologia Abbonamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TypeShow</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/TicketType__c.field-meta.xml
<CustomField>
    <fullName>TicketType__c</fullName>
    <label>Tipologia Offerta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TicketType</valueSetName>
    </valueSet>
</CustomField>

mdapi/globalValueSets/IssuanceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Emesso</fullName>
        <default>true</default>
        <label>Emesso</label>
    </customValue>
    <customValue>
        <fullName>Non Emesso</fullName>
    </customValue>
    <masterLabel>Tipologia Emissione</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/PaymentType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Donato</fullName>
        <default>true</default>
        <label>Donato</label>
    </customValue>
    <customValue>
        <fullName>Da pagare (a prezzo pieno)</fullName>
    </customValue>
    <customValue>
        <fullName>Da pagare (a prezzo scontato)</fullName>
    </customValue>
    <masterLabel>Tipologia Pagamento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TicketType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biglietto</fullName>
    </customValue>
    <customValue>
        <fullName>Abbonamento</fullName>
    </customValue>
    <customValue>
        <fullName>Esperienza</fullName>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>Biglietti Multipli</fullName>
        <isActive>false</isActive>
        <label>Biglietti Multipli</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <masterLabel>Tipologia Biglietto</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/TypeShow.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquario</fullName>
    </customValue>
    <customValue>
        <fullName>Centro Sportivo</fullName>
    </customValue>
    <customValue>
        <fullName>Cinema</fullName>
    </customValue>
    <customValue>
        <fullName>Circo</fullName>
    </customValue>
    <customValue>
        <fullName>Concerto</fullName>
    </customValue>
    <customValue>
        <fullName>Danza</fullName>
    </customValue>
    <customValue>
        <fullName>Evento (es. Festival, Rassegne)</fullName>
    </customValue>
    <customValue>
        <fullName>Gita scolastica</fullName>
    </customValue>
    <customValue>
        <fullName>Museo</fullName>
    </customValue>
    <customValue>
        <fullName>Parchi tematici, avventura, divertimento</fullName>
    </customValue>
    <customValue>
        <fullName>Partita (Stadio o Palazzetto dello sport)</fullName>
    </customValue>
    <customValue>
        <fullName>Teatro</fullName>
    </customValue>
    <customValue>
        <fullName>Altro</fullName>
    </customValue>
    <masterLabel>Tipologia Spettacolo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SiteController.cls
/**
 * @description       : Site controller
 * @author            : Seidor
**/
public without sharing class SiteController {
   
    /**
    * @description Get account by structure code
    * @param code : String
    * @return Account 
    **/
    @AuraEnabled
    public static Account getAccountByStructureCode(String code){
        try {
            return [SELECT Id FROM Account WHERE StructureCode__c = :code WITH SYSTEM_MODE LIMIT 1];
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }

    /**
    * @description Get tickets
    * @param accountId : Id
    * @return List<TicketAvailability__c> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<TicketAvailability__c> getTickets(Id accountId){
        try {
            return [SELECT Id, Name, Show__r.Name, Show__r.Type__c, Show__r.Datetime__c, StartValidity__c, EndValidity__c, 
                           State__c, TicketType__c, IssuanceType__c, PaymentType__c, Structure__r.Name, PriceFull__c, 
                           PriceDiscounted__c, OfferExpirationDate__c, NumberUses__c, SubscriptionName__c, SubscriptionType__c
                      FROM TicketAvailability__c 
                     WHERE Structure__c = :accountId
                      WITH SYSTEM_MODE
                  ORDER BY CreatedDate DESC];
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }

    /**
    * @description Delete ticket
    * @param ticketId : Id
    **/
    @AuraEnabled
    public static void deleteTicket(Id ticketId){
        try {
            TicketAvailability__c ticket = new TicketAvailability__c(Id = ticketId);
            delete as system ticket;
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }
}