force-app/main/default/objects/Account/fields/StructureCode__c.field-meta.xml
<CustomField>
    <fullName>StructureCode__c</fullName>
    <label>Codice Fornitore</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Structure.recordType-meta.xml
<RecordType>
    <fullName>Structure</fullName>
    <active>true</active>
    <label>Fornitore</label>
</RecordType>

force-app/main/default/objects/Show__c/Show__c.object-meta.xml
<CustomObject>
    <label>Spettacolo</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Show__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <label>Data e Ora</label>
    <type>DateTime</type>
</CustomField>

mdapi/objects/Show__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Struttura</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shows</relationshipLabel>
    <relationshipName>Shows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Show__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipologia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TypeShow</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/TicketAvailability__c.object-meta.xml
<CustomObject>
    <label>Offerta</label>
    <nameField>
        <displayFormat>Offerta-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offerte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/TicketAvailability__c/fields/EndValidity__c.field-meta.xml
<CustomField>
    <fullName>EndValidity__c</fullName>
    <label>Fine Validità</label>
    <type>DateTime</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/IssuanceType__c.field-meta.xml
<CustomField>
    <fullName>IssuanceType__c</fullName>
    <label>Tipologia Emissione</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TicketType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>IssuanceType</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/NumberUses__c.field-meta.xml
<CustomField>
    <fullName>NumberUses__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Numero Utilizzi</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/OfferExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpirationDate__c</fullName>
    <label>Data Scadenza Offerta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Tipologia Pagamento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IssuanceType__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PaymentType</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/PriceDiscounted__c.field-meta.xml
<CustomField>
    <fullName>PriceDiscounted__c</fullName>
    <label>Prezzo Scontato</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/PriceFull__c.field-meta.xml
<CustomField>
    <fullName>PriceFull__c</fullName>
    <label>Prezzo Intero</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Show__c.field-meta.xml
<CustomField>
    <fullName>Show__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spettacolo</label>
    <referenceTo>Show__c</referenceTo>
    <relationshipName>Biglietti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/StartValidity__c.field-meta.xml
<CustomField>
    <fullName>StartValidity__c</fullName>
    <label>Inizio Validità</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TicketAvailability__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Stato</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponibile</fullName>
                <default>true</default>
                <label>Disponibile</label>
            </value>
            <value>
                <fullName>Prenotato</fullName>
            </value>
            <value>
                <fullName>Utilizzato</fullName>
            </value>
            <value>
                <fullName>Scaduto</fullName>
            </value>
            <value>
                <fullName>Fatturato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornitore</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>L&apos;Account deve essere di tipo Struttura</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Structure</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offerte (Struttura)</relationshipLabel>
    <relationshipName>TicketAvailabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/TicketAvailability__c/fields/TicketType__c.field-meta.xml
<CustomField>
    <fullName>TicketType__c</fullName>
    <label>Tipologia Offerta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TicketType</valueSetName>
    </valueSet>
</CustomField>

mdapi/globalValueSets/IssuanceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Emesso</fullName>
        <default>true</default>
        <label>Emesso</label>
    </customValue>
    <customValue>
        <fullName>Non Emesso</fullName>
    </customValue>
    <masterLabel>Tipologia Emissione</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/PaymentType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Donato</fullName>
        <default>true</default>
        <label>Donato</label>
    </customValue>
    <customValue>
        <fullName>Da pagare (a prezzo pieno)</fullName>
    </customValue>
    <customValue>
        <fullName>Da pagare (a prezzo scontato)</fullName>
    </customValue>
    <masterLabel>Tipologia Pagamento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TicketType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biglietto</fullName>
    </customValue>
    <customValue>
        <fullName>Abbonamento</fullName>
    </customValue>
    <customValue>
        <fullName>Esperienza</fullName>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedDonated</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non Emesso - Donato</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionNotIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Non emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>Biglietti Multipli</fullName>
        <isActive>false</isActive>
        <label>Biglietti Multipli</label>
    </customValue>
    <customValue>
        <fullName>SubscriptionIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Abbonamento Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidFull</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo pieno)</label>
    </customValue>
    <customValue>
        <fullName>TicketIssuedToBePaidDiscount</fullName>
        <isActive>false</isActive>
        <label>Biglietto Emesso - Da pagare (a prezzo scontato)</label>
    </customValue>
    <masterLabel>Tipologia Biglietto</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/TypeShow.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acquario</fullName>
    </customValue>
    <customValue>
        <fullName>Centro Sportivo</fullName>
    </customValue>
    <customValue>
        <fullName>Cinema</fullName>
    </customValue>
    <customValue>
        <fullName>Circo</fullName>
    </customValue>
    <customValue>
        <fullName>Concerto</fullName>
    </customValue>
    <customValue>
        <fullName>Danza</fullName>
    </customValue>
    <customValue>
        <fullName>Evento (es. Festival, Rassegne)</fullName>
    </customValue>
    <customValue>
        <fullName>Gita scolastica</fullName>
    </customValue>
    <customValue>
        <fullName>Museo</fullName>
    </customValue>
    <customValue>
        <fullName>Parchi tematici, avventura, divertimento</fullName>
    </customValue>
    <customValue>
        <fullName>Partita (Stadio o Palazzetto dello sport)</fullName>
    </customValue>
    <customValue>
        <fullName>Teatro</fullName>
    </customValue>
    <customValue>
        <fullName>Altro</fullName>
    </customValue>
    <masterLabel>Tipologia Spettacolo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SiteControllerTest.cls
@IsTest
private class SiteControllerTest {

    @testSetup
    static void setupData() {
        // Crea account di test
        Account acc = new Account(
            Name = 'Test Account',
            StructureCode__c = 'STRUCT123',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Structure').getRecordTypeId()
        );
        insert acc;

        Show__c show = new Show__c(
            Name = 'Spettacolo Test',
            Type__c = 'Concerto',
            Datetime__c = DateTime.now().addDays(1)
        );
        insert show;

        TicketAvailability__c ticket = new TicketAvailability__c(
            Structure__c = acc.Id,
            Show__c = show.Id,
            StartValidity__c = Date.today(),
            EndValidity__c = Date.today().addDays(5),
            State__c = 'Disponibile',
            TicketType__c = 'Biglietto',
            IssuanceType__c = 'Emesso',
            PaymentType__c = 'Da pagare (a prezzo scontato)',
            PriceFull__c = 20.00,
            PriceDiscounted__c = 15.00,
            OfferExpirationDate__c = Date.today().addDays(3),
            NumberUses__c = 1
        );
        insert ticket;
    }

    @IsTest
    static void testGetAccountByStructureCode() {
        Test.startTest();
        Account result = SiteController.getAccountByStructureCode('STRUCT123');
        Test.stopTest();

        System.assertNotEquals(null, result, 'L\'account non dovrebbe essere null');
    }

    @IsTest
    static void testGetTickets() {
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        List<TicketAvailability__c> tickets = SiteController.getTickets(acc.Id);
        Test.stopTest();

        System.assertNotEquals(null, tickets, 'La lista dei ticket non dovrebbe essere null');
    }

    @IsTest
    static void testDeleteTicket() {
        TicketAvailability__c ticket = [SELECT Id FROM TicketAvailability__c LIMIT 1];

        Test.startTest();
        SiteController.deleteTicket(ticket.Id);
        Test.stopTest();

        // Verifica che il record sia stato effettivamente cancellato
        System.assertEquals(true, [SELECT Id FROM TicketAvailability__c].isEmpty(), 'Il ticket dovrebbe essere stato cancellato');
    }

    @IsTest
    static void testGetAccountByStructureCodeNotFound() {
        Test.startTest();
        try {
            SiteController.getAccountByStructureCode('INVALID_CODE');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'Eccezione attesa');
        }
        Test.stopTest();
    }
}