mdapi/objects/Comune__c/Comune__c.object-meta.xml
<CustomObject>
    <label>Comune</label>
    <nameField>
        <label>Comune Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comuni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Comune__c/fields/Nome_Comune__c.field-meta.xml
<CustomField>
    <fullName>Nome_Comune__c</fullName>
    <label>Nome Comune</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

mdapi/objects/Comune__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Province_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comune__c/fields/Regione__c.field-meta.xml
<CustomField>
    <fullName>Regione__c</fullName>
    <label>Regione</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Global</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/Fattura_Shadow__c/Fattura_Shadow__c.object-meta.xml
<CustomObject>
    <label>Fattura Shadow</label>
    <nameField>
        <label>Fattura Shadow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fatture Shadow</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Fattura_Shadow__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <formula>Fattura__r.Totale_Fattura__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Fattura_Shadow__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Fatture Shadow</relationshipLabel>
    <relationshipName>Fatture_Shadow</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Fattura</label>
    <nameField>
        <displayFormat>Fattura-{00000000}</displayFormat>
        <label>Codice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fatture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Invoice__c/fields/Fattura_Shadow__c.field-meta.xml
<CustomField>
    <fullName>Fattura_Shadow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fattura Shadow</label>
    <referenceTo>Fattura_Shadow__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Overview_Budget_per_Anno__c.field-meta.xml
<CustomField>
    <fullName>Overview_Budget_per_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Budget per Anno</label>
    <referenceTo>Overview_Budget_per_Anno__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Fatture</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Province_Global</valueSetName>
    </valueSet>
</CustomField>

mdapi/objects/Invoice__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Reporting_Year__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Overview Donatore per Anno</label>
    <referenceTo>Reporting_Year__c</referenceTo>
    <relationshipLabel>Fatture</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Total_Duration_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Duration_in_minutes__c</fullName>
    <label>Total Duration (in minutes)</label>
    <summarizedField>Visit__c.Duration_in_minutes__c</summarizedField>
    <summaryForeignKey>Visit__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Number_of_Visits__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Visits__c</fullName>
    <label>Total Number of Visits</label>
    <summarizedField>Visit__c.Quantity__c</summarizedField>
    <summaryForeignKey>Visit__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Totale_Biglietti__c.field-meta.xml
<CustomField>
    <fullName>Totale_Biglietti__c</fullName>
    <label>Totale Biglietti</label>
    <summarizedField>Ticket__c.Uses__c</summarizedField>
    <summaryForeignKey>Ticket__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

mdapi/objects/Invoice__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <formula>IF( Budget__r.Program__r.Name = &quot;Tempo Sospeso&quot;,  Totale_Ammontare_Visite__c , IF(Budget__r.Program__r.Name = &quot;Sorriso Sospeso&quot;,  Totale_Ammontare_Biglietti__c , 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Totale Fattura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/objects/Overview_Budget_per_Anno__c/Overview_Budget_per_Anno__c.object-meta.xml
<CustomObject>
    <label>Budget per Anno</label>
    <nameField>
        <label>Codice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Overview_Budget_per_Anno__c/fields/Totali_Budget_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Budget_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Budget Anno</label>
    <referenceTo>Totali_Budget_Anno__c</referenceTo>
    <relationshipLabel>Budget per Anno</relationshipLabel>
    <relationshipName>Budget_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reporting_Year__c/Reporting_Year__c.object-meta.xml
<CustomObject>
    <label>Donatore per Anno</label>
    <nameField>
        <label>Reporting Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donatori per Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Reporting_Year__c/fields/Totali_Donatore_Anno__c.field-meta.xml
<CustomField>
    <fullName>Totali_Donatore_Anno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Totali Donatore Anno</label>
    <referenceTo>Totali_Donatore_Anno__c</referenceTo>
    <relationshipLabel>Donatori per Anno</relationshipLabel>
    <relationshipName>Donatori_per_Anno</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_Visita__c/Tipo_Visita__c.object-meta.xml
<CustomObject>
    <label>Tipo Visita</label>
    <nameField>
        <label>Tipo Visita Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipi Visite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_Visita__c/fields/Tipo_Visita__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Visita__c</fullName>
    <label>Tipo Visita</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

mdapi/objects/Totali_Budget_Anno__c/Totali_Budget_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Budget Anno</label>
    <nameField>
        <label>Totali Budget Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Budget Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Totali_Donatore_Anno__c/Totali_Donatore_Anno__c.object-meta.xml
<CustomObject>
    <label>Totali Donatore Anno</label>
    <nameField>
        <label>Totali Donatore Anno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Totali Donatore Anno</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Totali_Donatore_Anno__c/fields/Totale_Fattura__c.field-meta.xml
<CustomField>
    <fullName>Totale_Fattura__c</fullName>
    <label>Totale Fattura</label>
    <summarizedField>Fattura_Shadow__c.Totale_Fattura_Static__c</summarizedField>
    <summaryForeignKey>Fattura_Shadow__c.Totali_Donatore_Anno__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visita Medica</label>
    <nameField>
        <displayFormat>Visita-{00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visite Mediche</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Visit__c/fields/Beneficiary_Type__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary_Type__c</fullName>
    <label>Beneficiary Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minorenne</fullName>
            </value>
            <value>
                <fullName>Donna</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi/objects/Visit__c/fields/Data_della_Visita__c.field-meta.xml
<CustomField>
    <fullName>Data_della_Visita__c</fullName>
    <label>Data della Visita</label>
    <type>Date</type>
</CustomField>

mdapi/objects/Visit__c/fields/Duration_in_minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_minutes__c</fullName>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapi/objects/Visit__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mdapi/objects/Visit__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Visit__c/fields/Tipo_Visita__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo Visita</label>
    <referenceTo>Tipo_Visita__c</referenceTo>
    <relationshipLabel>Visite Mediche</relationshipLabel>
    <relationshipName>Visite_Mediche</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/objects/Visit__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Province_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agrigento (AG)</fullName>
    </customValue>
    <customValue>
        <fullName>Alessandria (AL)</fullName>
    </customValue>
    <customValue>
        <fullName>Ancona (AN)</fullName>
    </customValue>
    <customValue>
        <fullName>Aosta (AO)</fullName>
    </customValue>
    <customValue>
        <fullName>Arezzo (AR)</fullName>
    </customValue>
    <customValue>
        <fullName>Ascoli Piceno (AP)</fullName>
    </customValue>
    <customValue>
        <fullName>Asti (AT)</fullName>
    </customValue>
    <customValue>
        <fullName>Avellino (AV)</fullName>
    </customValue>
    <customValue>
        <fullName>Bari (BA)</fullName>
    </customValue>
    <customValue>
        <fullName>Barletta-Andria-Trani (BT)</fullName>
    </customValue>
    <customValue>
        <fullName>Belluno (BL)</fullName>
    </customValue>
    <customValue>
        <fullName>Benevento (BN)</fullName>
    </customValue>
    <customValue>
        <fullName>Bergamo (BG)</fullName>
    </customValue>
    <customValue>
        <fullName>Biella (BI)</fullName>
    </customValue>
    <customValue>
        <fullName>Bologna (BO)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolzano/Bozen (BZ)</fullName>
    </customValue>
    <customValue>
        <fullName>Brescia (BS)</fullName>
    </customValue>
    <customValue>
        <fullName>Brindisi (BR)</fullName>
    </customValue>
    <customValue>
        <fullName>Cagliari (CA)</fullName>
    </customValue>
    <customValue>
        <fullName>Caltanissetta (CL)</fullName>
    </customValue>
    <customValue>
        <fullName>Campobasso (CB)</fullName>
    </customValue>
    <customValue>
        <fullName>Caserta (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>Catania (CT)</fullName>
    </customValue>
    <customValue>
        <fullName>Catanzaro (CZ)</fullName>
    </customValue>
    <customValue>
        <fullName>Chieti (CH)</fullName>
    </customValue>
    <customValue>
        <fullName>Como (CO)</fullName>
    </customValue>
    <customValue>
        <fullName>Cosenza (CS)</fullName>
    </customValue>
    <customValue>
        <fullName>Cremona (CR)</fullName>
    </customValue>
    <customValue>
        <fullName>Crotone (KR)</fullName>
    </customValue>
    <customValue>
        <fullName>Cuneo (CN)</fullName>
    </customValue>
    <masterLabel>Province</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/Region_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abruzzo</fullName>
    </customValue>
    <customValue>
        <fullName>Basilicata</fullName>
    </customValue>
    <customValue>
        <fullName>Calabria</fullName>
    </customValue>
    <customValue>
        <fullName>Campania</fullName>
    </customValue>
    <customValue>
        <fullName>Emilia-Romagna</fullName>
    </customValue>
    <customValue>
        <fullName>Friuli-Venezia Giulia</fullName>
    </customValue>
    <customValue>
        <fullName>Lazio</fullName>
    </customValue>
    <customValue>
        <fullName>Liguria</fullName>
    </customValue>
    <customValue>
        <fullName>Lombardia</fullName>
    </customValue>
    <customValue>
        <fullName>Marche</fullName>
    </customValue>
    <customValue>
        <fullName>Molise</fullName>
    </customValue>
    <customValue>
        <fullName>Piemonte</fullName>
    </customValue>
    <customValue>
        <fullName>Puglia</fullName>
    </customValue>
    <customValue>
        <fullName>Sardegna</fullName>
    </customValue>
    <customValue>
        <fullName>Sicilia</fullName>
    </customValue>
    <customValue>
        <fullName>Toscana</fullName>
    </customValue>
    <customValue>
        <fullName>Trentino-Alto Adige</fullName>
    </customValue>
    <customValue>
        <fullName>Umbria</fullName>
    </customValue>
    <customValue>
        <fullName>Valle d&apos;Aosta</fullName>
    </customValue>
    <customValue>
        <fullName>Veneto</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

mdapi/classes/FlowUtils.cls
public with sharing class FlowUtils {
  /*────────────────────────  METODI PUBBLICI  ────────────────────────*/

  /*──────────────────────── 1) API pubbliche ─────────────────────*/

  @AuraEnabled(cacheable=true)
  public static String convertToJSON(List<SObject> records) {
    try {
      return JSON.serialize(records);
    } catch (Exception e) {
      return '{"error": "' + e.getMessage() + '"}';
    }
  }

  /** Inserisce Visit__c da JSON replicando la logica “Crea Comune”.
   *  Se tipoVisitaId è assente ma è presente il nome (tipoVisita),
   *  crea o riutilizza un record Tipo_Visita__c con quel Name e lo collega.
   */
  @AuraEnabled
  public static List<Id> insertVisitaRecordsFromJSONString(String jsonString) {
    /* ─ 1. Parse e prima validazione */
    if (String.isBlank(jsonString))
      throw new AuraHandledException('Errore: Il JSON in input è vuoto.');
    Object parsedObj = JSON.deserializeUntyped(jsonString);
    if (!(parsedObj instanceof List<Object>))
      throw new AuraHandledException(
        'Errore: Il JSON ricevuto non è una lista.'
      );

    List<Visit__c> visitaRecords = new List<Visit__c>();
    /*  lista “richieste Comune”  { chiave, nome, prov, reg }           */
    List<ComuneRequest> comuniRichiesti = new List<ComuneRequest>();
    /*  nomi Tipo_Visita da garantire (se manca Id) */
    Set<String> tipoNamesToEnsure = new Set<String>();
    /*  parallel list per tenere il nome associato ad ogni Visit */
    List<String> tipoNameByIndex = new List<String>();

    for (Object obj : (List<Object>) parsedObj) {
      if (!(obj instanceof Map<String, Object>))
        continue;
      Map<String, Object> rec = (Map<String, Object>) obj;

      /* ---------- Campi obbligatori Visit__c ---------- */
      if (rec.get('invoiceId') == null)
        throw new AuraHandledException(
          'Errore: Il campo Fattura è obbligatorio.'
        );
      // Richiede almeno un nome per il tipo visita
      if (rec.get('tipoVisita') == null && rec.get('tipoVisitaId') == null)
        throw new AuraHandledException('Errore: Il Tipo Visita è obbligatorio.');

      String nome = (String) rec.get('comune');
      String prov = (String) rec.get('provincia');
      String reg = (String) rec.get('regione');
      if (String.isBlank(nome) || String.isBlank(prov) || String.isBlank(reg))
        throw new AuraHandledException(
          'Errore: Comune, Provincia e Regione sono obbligatori.'
        );

      /* ---------- popolazione Visit__c ---------- */
      Visit__c v = new Visit__c();
      Id invoiceId = toIdSafe(rec.get('invoiceId'));
      if (invoiceId == null)
        throw new AuraHandledException('Errore: Id Fattura non valido o mancante.');
      v.Invoice__c = invoiceId;
      Id tipoId = toIdSafe(rec.get('tipoVisitaId'));
      String tipoName = (String) rec.get('tipoVisita');
      v.Tipo_Visita__c = tipoId; // può essere null: lo risolviamo dopo
      v.Visit_Type__c = tipoName;
      v.Beneficiary_Type__c = (String) rec.get('beneficiaryType');
      v.Quantity__c = toIntegerSafe(rec.get('numeroVisite'));
      v.Duration_in_minutes__c = toIntegerSafe(rec.get('totaleMinuti'));
      v.Amount__c = toDecimalSafe(rec.get('amount'));
      v.Data_della_Visita__c = toDateSafe(rec.get('dataVisita'));
      v.City__c = nome;
      v.Province__c = prov;
      v.Region__c = reg;

      // Validazioni minime lato server per errori chiari
      if (String.isBlank(v.Visit_Type__c))
        throw new AuraHandledException('Errore: Il Nome del Tipo Visita è obbligatorio.');
      if (String.isBlank(v.Beneficiary_Type__c))
        throw new AuraHandledException('Errore: Seleziona il Tipo Beneficiario.');
      if (v.Quantity__c == null || v.Quantity__c <= 0)
        throw new AuraHandledException('Errore: Numero di Visite deve essere maggiore di 0.');
      if (v.Duration_in_minutes__c == null || v.Duration_in_minutes__c <= 0)
        throw new AuraHandledException('Errore: Totale Minuti di Visita deve essere maggiore di 0.');

      visitaRecords.add(v);
      comuniRichiesti.add(new ComuneRequest(nome, prov, reg));
      tipoNameByIndex.add(tipoName);
      if (tipoId == null && !String.isBlank(tipoName))
        tipoNamesToEnsure.add(tipoName.trim());
    }

    /* ─ 2. Up-sert comuni (solo se necessario) */
    Map<String, Comune__c> comuniMap = upsertComuni(comuniRichiesti);
    // Se in futuro vorrai salvare il lookup:
    // for (Visit__c v : visitaRecords)
    //     v.Comune__c = comuniMap.get(buildComuneKey(v.City__c,v.Province__c,v.Region__c)).Id;

    /* ─ 3. Up-sert Tipi Visita mancanti e collega gli Id */
    if (!tipoNamesToEnsure.isEmpty()) {
      Map<String, Id> name2Id = upsertTipoVisiteByName(tipoNamesToEnsure);
      for (Integer i = 0; i < visitaRecords.size(); i++) {
        if (visitaRecords[i].Tipo_Visita__c == null) {
          String n = tipoNameByIndex[i];
          if (!String.isBlank(n)) {
            Id rid = name2Id.get(n.trim().toLowerCase());
            if (rid != null) visitaRecords[i].Tipo_Visita__c = rid;
          }
        }
      }
    }
    // Fallback robusto: se ancora mancasse l'Id ma è presente il nome, tenta un ultimo upsert puntuale
    Set<String> lastMissing = new Set<String>();
    for (Integer i = 0; i < visitaRecords.size(); i++) {
      if (visitaRecords[i].Tipo_Visita__c == null) {
        String n = tipoNameByIndex[i];
        if (!String.isBlank(n)) lastMissing.add(n.trim());
      }
    }
    if (!lastMissing.isEmpty()) {
      Map<String, Id> name2Id2 = upsertTipoVisiteByName(lastMissing);
      for (Integer i = 0; i < visitaRecords.size(); i++) {
        if (visitaRecords[i].Tipo_Visita__c == null) {
          String n = tipoNameByIndex[i];
          if (!String.isBlank(n)) {
            Id rid = name2Id2.get(n.trim().toLowerCase());
            if (rid != null) visitaRecords[i].Tipo_Visita__c = rid;
          }
        }
      }
    }
    // Se per qualche motivo non riusciamo ancora a popolare il lookup, alza errore esplicito
    for (Integer i = 0; i < visitaRecords.size(); i++) {
      if (visitaRecords[i].Tipo_Visita__c == null) {
        throw new AuraHandledException('Errore: Tipo Visita non riconosciuto: ' + (tipoNameByIndex[i] == null ? '' : tipoNameByIndex[i]));
      }
    }

    /* ─ 4. Insert visite & output */
    try {
      insert visitaRecords;
    } catch (DmlException e) {
      // Espone un messaggio leggibile al client
      String msg = e.getDmlMessage(0);
      throw new AuraHandledException('Errore salvataggio Visite: ' + msg);
    }
    List<Id> outIds = new List<Id>();
    for (Visit__c v : visitaRecords)
      outIds.add(v.Id);
    return outIds;
  }

  /** Aggiorna Visit__c esistenti da JSON. Ogni item deve contenere visitId. */
  @AuraEnabled
  public static List<Id> updateVisitaRecordsFromJSONString(String jsonString) {
    if (String.isBlank(jsonString))
      throw new AuraHandledException('Errore: Il JSON in input è vuoto.');
    Object parsedObj = JSON.deserializeUntyped(jsonString);
    if (!(parsedObj instanceof List<Object>))
      throw new AuraHandledException('Errore: Il JSON ricevuto non è una lista.');

    List<Visit__c> updates = new List<Visit__c>();
    List<ComuneRequest> comuniRichiesti = new List<ComuneRequest>();
    Set<String> tipoNamesToEnsure = new Set<String>();
    List<String> tipoNameByIndex = new List<String>();

    for (Object obj : (List<Object>) parsedObj) {
      if (!(obj instanceof Map<String, Object>)) continue;
      Map<String, Object> rec = (Map<String, Object>) obj;
      Id vId = toIdSafe(rec.get('visitId'));
      if (vId == null)
        throw new AuraHandledException('Errore: manca l\'Id della visita da aggiornare.');

      String nome = (String) rec.get('comune');
      String prov = (String) rec.get('provincia');
      String reg = (String) rec.get('regione');
      if (String.isBlank(nome) || String.isBlank(prov) || String.isBlank(reg))
        throw new AuraHandledException('Errore: Comune, Provincia e Regione sono obbligatori.');

      Visit__c v = new Visit__c();
      v.Id = vId;
      Id tipoId = toIdSafe(rec.get('tipoVisitaId'));
      String tipoName = (String) rec.get('tipoVisita');
      if (tipoId != null) v.Tipo_Visita__c = tipoId;
      if (tipoName != null) v.Visit_Type__c = tipoName;
      v.Beneficiary_Type__c = (String) rec.get('beneficiaryType');
      v.Quantity__c = toIntegerSafe(rec.get('numeroVisite'));
      v.Duration_in_minutes__c = toIntegerSafe(rec.get('totaleMinuti'));
      v.Amount__c = toDecimalSafe(rec.get('amount'));
      v.Data_della_Visita__c = toDateSafe(rec.get('dataVisita'));
      v.City__c = nome;
      v.Province__c = prov;
      v.Region__c = reg;
      updates.add(v);
      comuniRichiesti.add(new ComuneRequest(nome, prov, reg));
      tipoNameByIndex.add(tipoName);
      if (tipoId == null && !String.isBlank(tipoName))
        tipoNamesToEnsure.add(tipoName.trim());
    }

    upsertComuni(comuniRichiesti);
    if (!tipoNamesToEnsure.isEmpty()) {
      Map<String, Id> name2Id = upsertTipoVisiteByName(tipoNamesToEnsure);
      for (Integer i = 0; i < updates.size(); i++) {
        if (updates[i].Tipo_Visita__c == null) {
          String n = tipoNameByIndex[i];
          if (!String.isBlank(n)) {
            Id rid = name2Id.get(n.trim().toLowerCase());
            if (rid != null) updates[i].Tipo_Visita__c = rid;
          }
        }
      }
    }
    // Fallback per update
    Set<String> lastMissingUp = new Set<String>();
    for (Integer i = 0; i < updates.size(); i++) {
      if (updates[i].Tipo_Visita__c == null) {
        String n = tipoNameByIndex[i];
        if (!String.isBlank(n)) lastMissingUp.add(n.trim());
      }
    }
    if (!lastMissingUp.isEmpty()) {
      Map<String, Id> name2Id3 = upsertTipoVisiteByName(lastMissingUp);
      for (Integer i = 0; i < updates.size(); i++) {
        if (updates[i].Tipo_Visita__c == null) {
          String n = tipoNameByIndex[i];
          if (!String.isBlank(n)) {
            Id rid = name2Id3.get(n.trim().toLowerCase());
            if (rid != null) updates[i].Tipo_Visita__c = rid;
          }
        }
      }
    }
    try {
      update updates;
    } catch (DmlException e) {
      String msg = e.getDmlMessage(0);
      throw new AuraHandledException('Errore aggiornamento Visite: ' + msg);
    }
    List<Id> ids = new List<Id>();
    for (Visit__c v : updates) ids.add(v.Id);

    // Allinea i valori statici della Fattura Shadow collegata alle visite aggiornate
    alignFatturaShadowStaticValues(new Set<Id>(ids));

    return ids;
  }

  /*──────────────────────── 2) NUOVO helper pubblico ─────────────*/

  /**
   * Riceve una lista di triple (nome, provincia, regione) e restituisce
   * una mappa chiave → record Comune__c contenente sia i record già
   * esistenti sia quelli appena creati.
   */
  public class ComuneRequest {
    public String nome, prov, reg;
    public ComuneRequest(String n, String p, String r) {
      nome = n;
      prov = p;
      reg = r;
    }
  }

  @AuraEnabled(cacheable=true)
  public static Map<String, Comune__c> upsertComuni(List<ComuneRequest> reqs) {
    Map<String, Comune__c> result = new Map<String, Comune__c>();
    if (reqs == null || reqs.isEmpty())
      return result;

    Set<String> nomiDaQuery = new Set<String>();
    for (ComuneRequest cr : reqs) {
      String key = buildComuneKey(cr.nome, cr.prov, cr.reg);
      nomiDaQuery.add(cr.nome);
      // inizialmente mettiamo null, poi lo riempiremo
      if (!result.containsKey(key))
        result.put(key, null);
    }

    /* 1. Query esistenti */
    if (!nomiDaQuery.isEmpty()) {
      for (Comune__c c : [
        SELECT Id, Nome_Comune__c, Provincia__c, Regione__c
        FROM Comune__c
        WHERE Nome_Comune__c IN :nomiDaQuery
      ]) {
        String k = buildComuneKey(
          c.Nome_Comune__c,
          c.Provincia__c,
          c.Regione__c
        );
        result.put(k, c);
      }
    }

    /* 2. Individua quelli da inserire */
    List<Comune__c> toInsert = new List<Comune__c>();
    for (ComuneRequest cr : reqs) {
      String k = buildComuneKey(cr.nome, cr.prov, cr.reg);
      if (result.get(k) == null) {
        Comune__c nc = new Comune__c(
          Nome_Comune__c = cr.nome,
          Provincia__c = cr.prov,
          Regione__c = cr.reg
        );
        toInsert.add(nc);
        result.put(k, nc); // placeholder, verrà ri-id-ato dopo l’insert
      }
    }
    if (!toInsert.isEmpty())
      insert toInsert;

    return result; // contiene i record definitivi (Id incluso)
  }

  /*──────────────────  METODI AUSILIARI  ──────────────────*/

  // Chiave “nome|provincia|regione” case-insensitive
  private static String buildComuneKey(String nome, String prov, String reg) {
    return (String.isBlank(nome) ? '' : nome.trim().toLowerCase()) +
      '|' +
      (String.isBlank(prov) ? '' : prov.trim().toLowerCase()) +
      '|' +
      (String.isBlank(reg) ? '' : reg.trim().toLowerCase());
  }

  // Crea (se mancante) i record Tipo_Visita__c in base al Name e
  // restituisce una mappa nameLowerCase → Id
  private static Map<String, Id> upsertTipoVisiteByName(Set<String> names) {
    Map<String, Id> out = new Map<String, Id>();
    if (names == null || names.isEmpty()) return out;

    // Normalizza input
    Set<String> normalized = new Set<String>();
    for (String n : names)
      if (!String.isBlank(n)) normalized.add(n.trim());

    if (normalized.isEmpty()) return out;

    // 1) Query esistenti per Name OPPURE per campo univoco Tipo_Visita__c
    for (Tipo_Visita__c tv : [
      SELECT Id, Name, Tipo_Visita__c
      FROM Tipo_Visita__c
      WHERE Name IN :normalized OR Tipo_Visita__c IN :normalized
    ]) {
      if (!String.isBlank(tv.Name)) out.put(tv.Name.trim().toLowerCase(), tv.Id);
      if (!String.isBlank(tv.Tipo_Visita__c)) out.put(tv.Tipo_Visita__c.trim().toLowerCase(), tv.Id);
    }

    // 2) Inserisci mancanti: serve valorizzare ANCHE il campo richiesto univoco Tipo_Visita__c
    List<Tipo_Visita__c> toInsert = new List<Tipo_Visita__c>();
    for (String n : normalized) {
      String key = n.trim().toLowerCase();
      if (!out.containsKey(key)) {
        toInsert.add(new Tipo_Visita__c(Name = n, Tipo_Visita__c = n));
      }
    }
    if (!toInsert.isEmpty()) {
      try {
        insert toInsert;
      } catch (DmlException e) {
        // Propaga un errore leggibile
        throw new AuraHandledException('Errore creazione Tipo_Visita__c: ' + e.getDmlMessage(0));
      }
      for (Tipo_Visita__c tv : toInsert) {
        if (!String.isBlank(tv.Name)) out.put(tv.Name.trim().toLowerCase(), tv.Id);
        if (!String.isBlank(tv.Tipo_Visita__c)) out.put(tv.Tipo_Visita__c.trim().toLowerCase(), tv.Id);
      }
    }
    return out;
  }

  private static Integer toIntegerSafe(Object o) {
    if (o == null)
      return 0;
    try {
      return Integer.valueOf(o.toString());
    } catch (Exception e) {
      return 0;
    }
  }

  private static Decimal toDecimalSafe(Object o) {
    if (o == null)
      return 0.00;
    try {
      return Decimal.valueOf(o.toString());
    } catch (Exception e) {
      return 0.00;
    }
  }

  private static Date toDateSafe(Object o) {
    if (o == null)
      return null;
    try {
      return Date.valueOf(o.toString());
    } catch (Exception e) {
      return null;
    }
  }

  // Converte un valore generico in Id se valido, altrimenti null
  private static Id toIdSafe(Object o) {
    if (o == null) return null;
    String s = String.valueOf(o);
    if (String.isBlank(s)) return null;
    try {
      return (Id) s;
    } catch (Exception e) {
      return null;
    }
  }

  /**
   * Richiama il Flow "Aggiorna Valori Statici Fattura Shadow" per ciascuna
   * fattura shadow collegata alle visite aggiornate, in modo da riallineare
   * i campi statici dopo la modifica delle visite.
   */
  private static void alignFatturaShadowStaticValues(Set<Id> visitIds) {
    if (visitIds == null || visitIds.isEmpty()) return;

    // 1) Recupera le fatture associate alle visite aggiornate
    Set<Id> invoiceIds = new Set<Id>();
    for (Visit__c v : [
      SELECT Invoice__c
      FROM Visit__c
      WHERE Id IN :visitIds AND Invoice__c != NULL
    ]) {
      invoiceIds.add(v.Invoice__c);
    }

    if (invoiceIds.isEmpty()) return;

    // 2) Recupera le Fattura_Shadow collegate alle fatture
    Set<Id> shadowIds = new Set<Id>();
    Map<Id, Invoice__c> invoiceByShadow = new Map<Id, Invoice__c>();
    for (Invoice__c inv : [
      SELECT Fattura_Shadow__c,
             Totale_Fattura__c,
             Totale_Biglietti__c,
             Total_Number_of_Visits__c,
             Total_Duration_in_minutes__c,
             Overview_Budget_per_Anno__r.Totali_Budget_Anno__c,
             Reporting_Year__r.Totali_Donatore_Anno__c
      FROM Invoice__c
      WHERE Id IN :invoiceIds AND Fattura_Shadow__c != NULL
    ]) {
      if (inv.Fattura_Shadow__c != null) {
        shadowIds.add(inv.Fattura_Shadow__c);
        invoiceByShadow.put(inv.Fattura_Shadow__c, inv);
      }
    }

    if (shadowIds.isEmpty() || Test.isRunningTest()) return;

    // 3) Invoca il Flow per ciascuna Fattura_Shadow
    for (Id shadowId : shadowIds) {
      try {
        Invoice__c inv = invoiceByShadow.get(shadowId);
        Map<String, Object> params = new Map<String, Object>{
          'recordId' => shadowId,
          'input_skip_lookup' => true
        };
        if (inv != null) {
          params.put('input_totale_fattura', inv.Totale_Fattura__c);
          params.put('input_totale_durata', inv.Total_Duration_in_minutes__c);
          params.put('input_totale_visite', inv.Total_Number_of_Visits__c);
          params.put('input_totale_biglietti', inv.Totale_Biglietti__c);
          params.put(
            'input_totali_budget_id',
            inv.Overview_Budget_per_Anno__r != null
              ? inv.Overview_Budget_per_Anno__r.Totali_Budget_Anno__c
              : null
          );
          params.put(
            'input_totali_donatore_id',
            inv.Reporting_Year__r != null
              ? inv.Reporting_Year__r.Totali_Donatore_Anno__c
              : null
          );
        }
        Flow.Interview.Aggiorna_Valori_Statici_Fattura_Shadow_autolaunched flowInstance =
          new Flow.Interview.Aggiorna_Valori_Statici_Fattura_Shadow_autolaunched(params);
        flowInstance.start();
      } catch (Exception e) {
        System.debug('alignFatturaShadowStaticValues – errore su shadow ' + shadowId + ': ' + e.getMessage());
      }
    }
  }

  /*──────────────────────── 3) DELETE visite ─────────────────────*/
  @AuraEnabled
  public static void deleteVisits(List<Id> visitIds) {
    if (visitIds == null || visitIds.isEmpty()) return;
    List<Visit__c> toDelete = [SELECT Id FROM Visit__c WHERE Id IN :visitIds];
    if (!toDelete.isEmpty()) delete toDelete;
  }

  /*──────────────────────── 4) GET visita per precompilazione ───*/
  @AuraEnabled(cacheable=true)
  public static Visit__c getVisitById(Id visitId) {
    if (visitId == null) return null;
    List<Visit__c> res = [
      SELECT Id, Invoice__c, Tipo_Visita__c, Tipo_Visita__r.Name, Visit_Type__c, Beneficiary_Type__c,
             Quantity__c, Duration_in_minutes__c, Amount__c, Data_della_Visita__c,
             City__c, Province__c, Region__c
      FROM Visit__c
      WHERE Id = :visitId
      LIMIT 1
    ];
    return res.isEmpty() ? null : res[0];
  }
}