mdapi/objects/Configurazioni__c/Configurazioni__c.object-meta.xml
<CustomObject>
    <label>Configurazione</label>
    <nameField>
        <displayFormat>CFG-{0000}</displayFormat>
        <label>Configurazione Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configurazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configurazioni__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Configurazioni</relationshipLabel>
    <relationshipName>Configurazioni</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Configurazioni__c/fields/Attiva__c.field-meta.xml
<CustomField>
    <fullName>Attiva__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attiva</label>
    <type>Checkbox</type>
</CustomField>

mdapi/objects/Configurazioni__c/fields/Nome_Configurazione__c.field-meta.xml
<CustomField>
    <fullName>Nome_Configurazione__c</fullName>
    <label>Nome Configurazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configurazioni__c/fields/Nome_Funzionalita__c.field-meta.xml
<CustomField>
    <fullName>Nome_Funzionalita__c</fullName>
    <label>Nome Funzionalità</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/objects/Configurazioni__c/fields/On_Off__c.field-meta.xml
<CustomField>
    <fullName>On_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Off</label>
    <type>Checkbox</type>
</CustomField>

mdapi/objects/Configurazioni__c/fields/Tipo_Configurazione__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Configurazione__c</fullName>
    <label>Tipo Configurazione</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

mdapi/classes/ConfigurazioniFlowHelperTest.cls
@IsTest
private class ConfigurazioniFlowHelperTest {
    @IsTest
    static void testEvaluatePrestazioneGratuita() {
        Account enabledAccount = new Account(Name = 'Enabled Account');
        insert enabledAccount;

        Account disabledAccount = new Account(Name = 'Disabled Account');
        insert disabledAccount;

        Configurazioni__c disabledConfiguration = new Configurazioni__c(
            Account__c = disabledAccount.Id,
            Attiva__c = true,
            Nome_Configurazione__c = 'Prestazione Gratuita Off',
            Tipo_Configurazione__c = 'Funzionalità on/off',
            Nome_Funzionalita__c = 'Prestazione Gratuita',
            On_Off__c = false
        );
        insert disabledConfiguration;

        Configurazioni__c enabledConfiguration = new Configurazioni__c(
            Account__c = enabledAccount.Id,
            Attiva__c = true,
            Nome_Configurazione__c = 'Prestazione Gratuita On',
            Tipo_Configurazione__c = 'Funzionalità on/off',
            Nome_Funzionalita__c = 'Prestazione Gratuita',
            On_Off__c = true
        );
        insert enabledConfiguration;

        List<Id> accountIds = new List<Id>{ disabledAccount.Id, enabledAccount.Id, null }; // null -> default true

        Test.startTest();
        List<Boolean> responses = ConfigurazioniFlowHelper.evaluatePrestazioneGratuita(accountIds);
        Test.stopTest();

        System.assertEquals(3, responses.size(), 'Three responses expected');
        System.assertEquals(false, responses[0],
            'Disabled configuration should return false');
        System.assertEquals(true, responses[1],
            'Enabled configuration should return true');
        System.assertEquals(true, responses[2],
            'Null account should default to true');
    }
}